### ISSUE TITLE
Module not found: pycast.Caster

### ISSUE THREAD

**Issue by CZ2021** [clariusdev/cast#10]
We currently test a demo device (L7 HD Scanner) and Mr Noethen (Territory Manager, Germany ) and Mrs. Thomas (Support) told us to create a issue tp provide a fast solution about the functions of the research packages.

•	Python version 3.7.7 
•	Pycast version pip install pycast==v0.1.5-alpha
o	Also: Github version GitHub - T-002/pycast: Python forecasting and smoothing library

Problem executing python examples:

(venv) C:\Users\E7111\Desktop\clarius_repo\cast\src\python>python pycaster.py --address 192.168.1.1 --port 43299
Traceback (most recent call last):
  File "pycaster.py", line 123, in <module>
    main()
  File "pycaster.py", line 84, in main
    cast = pycast.Caster(newProcessedImage, newRawImage, freezeFn, buttonsFn)
AttributeError: module 'pycast' has no attribute 'Caster'

--> Module Caster neither found in pip verison of pycast nor gitrhub version and even commit history

Please consider a fast answer, since we only have our demo device for 3 more days, to evaluate wether we need the research package or not.

**Comment by julien-l** [comment]
Hi, it seems you have another **pycast** installed via pip (https://pypi.org/project/pycast/), it may be conflicting with the Clarius **pycast**. These two Python packages have the same name, but the former is not related to Clarius. First uninstall **pycast**:

    pip uninstall pycast

Then obtain Clarius' own **pycast** library in the release section of this repository: https://github.com/clariusdev/cast/releases/.

Then follow the instructions here: https://github.com/clariusdev/cast/tree/master/src/python.

**Comment by CZ2021** [comment]
Hello, thank you that worked!

The Pycaster is working now, however when I start the QT no buttons are shown in the screen, it is just black and blank. The scanner is connected and when I press "freeze" or "unfreeze" on my tablet, the status changes from "image stooped" to "image running".

Also, can you tell me how to save the raw data? I know that raw data is obtained at the same time during B-mode imaging, but no data is recorded. I have saved images from life and from the frozen image, but neither worked. The research functions are enabled on our scanner and should work according to clarius support.

**Comment by clariusk** [comment]
- Black screen: If you're running on Windows, see note at bottom main page: https://github.com/clariusdev/cast
- Raw data: read more here: https://github.com/clariusdev/signalproc

**Comment by CZ2021** [comment]
Thank you, it works now
