### ISSUE TITLE
Clarius Mobile App v10.2 is released but the Cast Api v10.2 is not release.

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#106]
Hi,

We have seen Clarius Mobile App is updated on Apple Store to v10.2.
Unfortunately, our devices was automatically updated to this version and it doesn't work with our software that is using cast api v10.1.

Could you please release the new version of Cast?
It is urgent as we have to use it tomorrow.

Thank you.

**Comment by clariusk** [comment]
10.2 is a pilot release, we do not release API's until it makes the store, please downgrade your scanners back to 10.1

**Comment by nguyenvuduc** [comment]
Thank Kris, my bad. I have withdrawn from the TestFlight to downgrade the software back to 10.1.2 and the scanner back to 10.1.1.
