### ISSUE TITLE
Entirely black image, on various (Linux) systems

### ISSUE THREAD

**Issue by genericusername3** [clariusdev/cast#107]
Hi, we're trying to get the Python API wrappers to work but we're getting entirely black/transparent images on both 10.0.0 and 10.1.1, just like #99, #100 and #102. We've tried two different Linux systems without Nvidia GPUs (integrated Intel graphics), one with a GTX 645 (we're getting desperate) both with default drivers and `nvidia-driver-470`, as described in #102 (have yet to test `nvidia-driver-515`), all four configurations had the same problem, some with, some without GL error messages as in #100.

Until this is fixed, I would like to get _any_ working system up due to an upcoming presentation, so:
- Is there any way to know in advance whether a system is going to work?
- What hardware/OS/driver configuration(s) did you test the current API version with?
- Could switching to Windows for the time being help, even if using the API with Linux on the same machine is broken?
    - If so, does the API require a dedicated graphics card on Windows or would integrated graphics also work?

**Comment by clariusk** [comment]
we are investigating the root cause, at this point we don't have additional information on driver/gpu combinations that fail. If you are able to use a Windows systems, it should work well in the meantime.

**Comment by clariusk** [comment]
We have a new version out 10.2.2 which we recommend upgrading to - we have not fixed the opengl issue, however this version will allow you to connect to a probe without having to keep the Clarius App at the same version

Once you have upgraded, we would like to provide the next alpha library to test potential fixes. I can put this in the releases section under pre-release. To minimize uploads, please provide the python version and Ubuntu version you're using.

**Comment by clariusk** [comment]
@genericusername3 if this is still an issue, can you send over the GL error messages being shown, thanks

**Comment by clariusk** [comment]
sounds good, thank you!
