### ISSUE TITLE
cannot find -lcast

### ISSUE THREAD

**Issue by awdevlin** [clariusdev/cast#108]
Hello,

I've been trying to get Clarius Cast working in order to collect RF data from a probe using my laptop. I have been getting this error: "cannot find -lcast"

https://imgur.com/a/LqNPnLf

I believe this means that I need to create a lib folder here cast/desktop/scr/lib. If this is right, I'm having trouble locating the lib files that I need to copy. 

Thanks for any help you can provide.

**Comment by clariusk** [comment]
all binaries can be found here, https://github.com/clariusdev/cast/releases, thanks!

**Comment by awdevlin** [comment]
Great. I have unzipped the files for Windows into a lib folder in the src folder. 

I'm getting several new errors that say "undefined reference"

![image](https://user-images.githubusercontent.com/42992938/218560060-62d7f3de-5f12-4dba-9ec5-5893488380ce.png)

Is this something that has come up before?

**Comment by clariusk** [comment]
ensure the relative directory in your project file is actually the lib folder, or just make the directory explicit

**Comment by awdevlin** [comment]
I made the filepath explicit and the same issues happened.

I'm using Qt5. My colleague working on the same project said they have issues with Cast while using Qt6.

**Comment by clariusk** [comment]
I imagine it's still related to not finding the .lib file, as we cannot support users on compilation issues, but for information we use msvc 1929 (https://en.wikipedia.org/wiki/Microsoft_Visual_C)

**Comment by awdevlin** [comment]
I reinstalled QT and repeated setting everything up and it worked. I must have made some sort of error initially.
