### ISSUE TITLE
Issue with build of the API: missing inclusion file 'boost/program_options.hpp': No such file or directory

### ISSUE THREAD

**Issue by MirkoJ1991** [clariusdev/cast#110]
After downloading the source code and extracting the libraries of windows inside the path: desktop/src/lib, after configuring the project with the MSCV compiler Qt report a missing file 'boost/program_options.hpp'. Is there any step that i missed in the configuration of the Qt project?

**Comment by julien-l** [comment]
Hello, the Windows version currently requires the boost c++ libraries to be installed for program argument parsing, as noted in the readme. Go to the official website and you can download prebuilt binaries for Windows https://www.boost.org/users/download/.

**Comment by MirkoJ1991** [comment]
Hello,  following your instruction I downloaded the prebuilt boost c++ libraries (1_81_0) and installed them (through the .exe) in my C:\local folder. After adding the folder in the include path of the .pro file by adding the following line 

INCLUDEPATH += "C:\local\boost_1_81_0"

and after compiling it again, there was a further issue in the specific library:

- libboost_program_options-vc142-mt-gd-x64-1_81.lib

Which are the following steps? 
I apologise for the nuisance and thank you in advance, but as you may understand I have 0 expertise in building API from the source code and at this point, I am trying solutions blindly,

**Comment by julien-l** [comment]
What is the issue? If cannot find the lib, you may need to specify its location with `LIB` https://doc.qt.io/qt-6/qmake-variable-reference.html#libs like you did with `INCLUDEPATH` for headers.

**Comment by MirkoJ1991** [comment]
Yes indeed I think it is a problem of including the headers and the libraries correctly.

I added the following two lines in the .pro file:

INCLUDEPATH += "C:\local\boost_1_81_0" < WHERE I INSTALLED MY BOOST LIBRARIES
LIBS += "C:\local\boost_1_81_0\stage\lib\libboost_program_options-vc142-mt-gd-x64-1_81.lib" < WHERE IS LOCATED THE MISSING LIBRARY

However, even if apparently the building process finish without any error. As soon as i open the .exe located inside the new folder

build-caster-Desktop_Qt_6_4_2_MSVC2019_64bit-Debug/debug

A new pop up message specifiy that the cast.dll error is not found.

**Comment by julien-l** [comment]
Try moving the dll in the executable's folder.

**Comment by MirkoJ1991** [comment]
Done but nothing happens, going back to the compiler using the debug option i found this warning:

C:\local\boost_1_81_0\boost\throw_exception.hpp:166: warning: Debugger encountered an exception: Exception at 0x7ffb2365cd29, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance)
![0088](https://user-images.githubusercontent.com/59056937/221186687-4d42192b-3b8c-4f5a-ba60-359f7e635b75.png)

**Comment by julien-l** [comment]
Ensure you pass the correct command line arguments. Pass the `help` argument to the command line to see the available arguments. You need to pass the IP address of the probe, the listen port (both visible from clarius app once connected to probe).

**Comment by clariusk** [comment]
suggest you stay away from boost for windows if you can, no point in going through the hassle of integrating that library if you don't need to pass command line args - ie. just code into the program for now
