### ISSUE TITLE
Cast v10.2.2 crashes on Windows 10, non-Qt project

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#111]
My software crashes in cast.dll after upgrading the cast to v10.2.2. It was a memory access violation at 0x000000000.
The crash occurred after `cusCastConnect` was successfully invoked.

I tested the example and got another error at cusCastInitialize. Belows is the console output of cast_qt example:
![image](https://user-images.githubusercontent.com/5864656/221430698-0321e9dd-b7d7-4e01-b4e0-9e93496037f3.png)
![image](https://user-images.githubusercontent.com/5864656/221430722-53b9b18f-1794-4def-b284-514583fb6620.png)
![image](https://user-images.githubusercontent.com/5864656/221430758-6a10b2a3-8198-4254-bb89-0273b8eaf19b.png)

Development environment when compiling the cast_qt example:
- Cast v10.2.2
- Windows 10 Pro 22H2
- Qt 6.3.1
- Visual Studio 2019

Regards.

**Comment by julien-l** [comment]
According to the documentation of `SetProcessDpiAwarenessContext()`:

> Return value: ERROR_ACCESS_DENIED if the default API awareness mode for the process has already been set (via a previous API call or within the application manifest).

This call is performed by the Qt Windows platform plugin, it is out of our control so ensure your app does not set the DEPI mode via previous API call or application manifest.

**Comment by nguyenvuduc** [comment]
Thank Julien. I am using WPF for the GUI. I will check whether I can disable Dpi Awareness on my app's site.
I hope this error can be eliminated at the API site as the library should be independent of the app's GUI.

Anyway, I will update you later on how it is going.

**Comment by nguyenvuduc** [comment]
Hi Julien,
Did the example work on your computer? 
The screenshot of the error that I sent is generated by the example cast_qt of Clarius.

**Comment by clariusk** [comment]
please see the release note here: https://github.com/clariusdev/cast/releases, known issue in this version

**Comment by nguyenvuduc** [comment]
Thank Kris. I have changed the example to accept 0 as success when calling cusCastInit.
However, it crashes after receiving a few images. You might want to give it a look.
![image](https://user-images.githubusercontent.com/5864656/222049012-098e6b64-e454-4964-9f76-a50ee0571988.png)

Currently, our devices have been accidentally upgraded to v10.2.2, and couldn't use our software anymore due to this issue.
Do you have any suggestions on how to solve this? We have a clinic next week :(.

Thank you.

**Comment by nguyenvuduc** [comment]
Hi @julien-l ,
- You were right. That is a bug of the Clarius' example. I have temporally fixed it and it is working.
![image](https://user-images.githubusercontent.com/5864656/222938152-a82626f0-a5f5-4765-85d9-55482f36762b.png)


- However, it seems there is a breaking change in the Cast API v10.2.2 that makes my software crash. I can see there is an access violation to memory address 0x00000000 thrown by cast.dll.
To make sure this is not false. I have created a tiny software that just calls cusCastInit and cusCastConnect and it shows the same symptom.
![image](https://user-images.githubusercontent.com/5864656/222938163-cea7f002-7b1a-40e7-917a-205e18846e10.png)

- Could you please take a look? You can download the code from my GitHub. It is a Visual Studio 2019 C++ project with only 100 lines of code. I suspect the cast.dll is access something that is not available in Non-Qt environment.
https://github.com/nguyenvuduc/ClariusCastDllClientTestVsCpp/blob/main/ClariusCastDllClientTestVsCpp.cpp

Regards,

**Comment by nguyenvuduc** [comment]
Thank Kris. That will work. I really appreciate it.
Where can get the APK files? I couldn't find it on GitHub or Clarius' website. Regards,

**Comment by clariusk** [comment]
we have some APKs [here](https://github.com/clariusdev/mobileapi/releases), latest is 10.1.1, we can probably make a new repository to host all the major releases next week as well.

**Comment by nguyenvuduc** [comment]
Thank Kris

**Comment by J-Olejnik** [comment]
Hi @nguyenvuduc  @clariusk, 
I have been working with caster_qt example for a while now end these Debug Errors have always been there. From what I've learned you can just "ignore" them when running on debug mode, or run your code either on release or straight from .exe, so that they don't appear at all.
As for the access violation exception, I also have encountered this issue after updating cast.dll to v10.2.2. For me the exception is being thrown after calling cusCastUserFunction (for example after calling it with Freeze command, image is being frozen on the mobile device and exception stops desktop app from working).
Ss from VS:
![Capture](https://user-images.githubusercontent.com/108056647/223679220-ee3e6403-f119-4c6e-8188-764bd3244e9c.PNG)

Hope this helps and that this issue could be resolved in the nearest future.

**Comment by clariusk** [comment]
@J-Olejnik thanks, this is helpful

**Comment by clariusk** [comment]
hi, I found the issue, there was an issue when calling freeze or any user parameter, this will be fixed for 10.3 coming soon!
