### ISSUE TITLE
missing 'libcast.so' and 'pyclariuscast.so'

### ISSUE THREAD

**Issue by luohwu** [clariusdev/cast#112]
Dear clariusdev team,

How can I get these files? Do I missed something? I am using a demo device with enabled research bundle for 48 hours, and would like to try the research API feature. When I tried to run the python file on windows, 'libcast.so' and './pyclariuscast.so' cant be found. Thanks in advance for your help!

**Comment by julien-l** [comment]
https://github.com/clariusdev/cast/releases

**Comment by luohwu** [comment]
> https://github.com/clariusdev/cast/releases

Thanks Julien ,
It worked after I modified the file name from 'libcast.so' to 'cast.dll'.

**Comment by luohwu** [comment]
> https://github.com/clariusdev/cast/releases

Hi Julien,
After input the right IP address and port number and click 'connect' and 'run' in pysidercaster.py, I can get the streaming of the images. However, when the app starts, it shows 'Failed to initialized' in the message bar. I am wandering the impact of this warning. Should I ignore it directly?

**Comment by julien-l** [comment]
Can you provide a screenshot? Which app shows the "failed to initialize" message, the clarius app or caster example?

**Comment by luohwu** [comment]
Thanks for your fast feedback.

It's the python caster example.
![initialization failed](https://user-images.githubusercontent.com/76627876/221918080-7863a703-7371-430c-937b-4b0391f7256c.png)

And the following is the screenshot of streamming
![normal](https://user-images.githubusercontent.com/76627876/221918380-a8c171a7-1e94-41ee-af83-7e3837abd4b3.png)

**Comment by luohwu** [comment]
> Can you provide a screenshot? Which app shows the "failed to initialize" message, the clarius app or caster example?

Thanks for your fast feedback.

It's the python caster example.

![initialization failed](https://user-images.githubusercontent.com/76627876/221919731-168b2adf-400d-46ab-8e02-bfb1682df63e.png)

And the following is the screenshot of streaming
![normal](https://user-images.githubusercontent.com/76627876/221919799-f1c3b284-d604-4188-b60a-5ffb7850581f.png)

**Comment by julien-l** [comment]
Not sure what is wrong, do you have more detailed error message from the console logs?

**Comment by clariusk** [comment]
please see the release note for 10.2.2: https://github.com/clariusdev/cast/releases, explains the message

**Comment by luohwu** [comment]
@julien-l @clariusk  thanks for your help. now it's clear! Have a nice day!
