### ISSUE TITLE
Android  cast : setOutputSize(IMAGE_SIZE, IMAGE_SIZE) and userFunction(Flip) doesn't do anything

### ISSUE THREAD

**Issue by ganitps** [clariusdev/cast#115]
Hi

I tried using the methods setOutputSize, userFunction(Flip) like this:

```
cast.initialize(getCertDir(context)) { result -> Log.i(TAG, "cast initialize result: $result") }
cast.setOutputSize(IMAGE_SIZE, IMAGE_SIZE) 
cast.setFormat(ImageFormat.Uncompressed)
cast.userFunction(UserFunction.Flip, 0.0, {}) 
```

IMAGE_SIZE = 192. 
The images received in the callback newProcessedImage(buffer: ByteBuffer, info: ProcessedImageInfo, pos: Array<PosInfo>)
were still of size 800*800. and the images still x axis flipped . (not as seen in the Clarius application).

Any advice?

**Comment by julien-l** [comment]
The `initialize()` function is asynchronous, that is to say, when the function call returns, it does not necessarily mean the initialization is complete and therefore you should no try to call "set" functions on the cast lib yet. The cast lib signals completion by executing the callback passed to `initialize()`. Call the "set" function there:

    cast.initialize(getCertDir(context), result -> {
        Log.i(TAG, "cast initialize result: $result");
        if (result) {
            cast.setOutputSize(IMAGE_SIZE, IMAGE_SIZE);
            cast.setFormat(ImageFormat.Uncompressed);
            cast.userFunction(UserFunction.Flip, 0.0, {});
        }
    });

**Comment by ganitps** [comment]
Thank you @julien-l 
output size now changed as expected !
still I get the image flipped whether  I use '''cast.userFunction(UserFunction.Flip, 0.0, {});''' or not , 
any ideas about that?

**Comment by julien-l** [comment]
Hi @ganitps this is the expected behaviour: the "flip" function only flips the displayed image in the clarius app and not the image sent over cast. I reckon you'd like the streamed image to be the same as the displayed image, we will discuss it during our next engineering meeting and I will update you.
