### ISSUE TITLE
python lib: How to set/change image format sent from probe

### ISSUE THREAD

**Issue by Contused** [clariusdev/cast#117]
I have started working with the python library and have some technical questions regarding api calls.
Since I´m new to python dynamic libraries I don´t know where to find the documentation / code for the lib.

One of the question would be:

How do I change the Image format that is sent from the c3hd3?
In cast.h I found the following line: CAST_EXPORT int cusCastSetFormat(CusImageFormat format);
But I can´t seem to find the equivalent function for the python lib

**Comment by clariusk** [comment]
thanks for the note, this is missing from pyclariuscast, we'll add that for next release
