### ISSUE TITLE
Python Desktop app calling Linux files

### ISSUE THREAD

**Issue by LeahWosler** [clariusdev/cast#118]
The desktop app (https://github.com/clariusdev/cast/blob/master/desktop/src/python/pysidecaster.py)  contains code that tries to load linux libraries into windows python app causing errors. 

libcast = ctypes.CDLL('./libcast.so', ctypes.RTLD_GLOBAL) # load the libcast.so shared library
pyclariuscast = ctypes.cdll.LoadLibrary('./pyclariuscast.so') # load the pyclariuscast.so shared library

Removing this code and using the most up to date window's binaries (cast.dll and cast.lib) does not successfully make a connection. This code used to work before the latest update.

**Comment by clariusk** [comment]
as we distribute pyclariuscast with specific python versions, ensure you remove the version from the .so name (ie. remove 310 from pyclariuscast310.so)
