### ISSUE TITLE
Few Technical Issues with Our Institution's Clarius Package

### ISSUE THREAD

**Issue by rBirde** [clariusdev/cast#12]
Hi, 

I understand that this is not the place to cast technical questions other than those related to the Clarius Cast codes. Anyhow, I have contacted the Clarius Support team and I have been redirected to this page to ask any kinds of technical issues with the package which is weird. Here are a few:

The exams are not saved on the local device (which uses an up-to-date android platform) no matter the selected output format e.g., JPEG, or DICOM. It shows the following message: Unable to export exam from [date and time of the exam] to [selected format]. This is as though the application's got permission to the storage and the exams are successfully uploaded to the Clarius Cloud. This shouldn't be some complicated procedure and should be running smoothly as shown on the tutorial videos and manuscripts (That the app is designed so that the exam data are stored simply on the local device by default).

Also, we are interested in Raw data. I am able to capture the raw data and send them to the Clarius cloud, and then use them with the MATLAB and Python functions/classes provided which is great. Although the problem of saving raw data on the android device remains still, as no data (not even jpeg images) are stored on the device

In a different matter, I have tried the Mobile API and run them on the device with android studio. When I press "connect" a message is shown: Connected: true. However, I cannot get any other features to work. An "Error: no license" message is shown for any kinds of requests. This is as though I follow all the necessary steps to make use of the API e.g., connecting the scanner and running the Clarius App in the background. Does this necessarily mean that our scanner does not cover this API? The same situation holds true for the Clarius Cast.

Does the mobile API allow capturing raw data? (because I don't see the option in the quickstart app but I was thinking it might do by checking some options on the clarius app as is done directly on the app itself) 

Thank you very much for your time, consideration and for your help in advance.

Best regards,
Reza

**Comment by clariusk** [comment]
- Yes, we've seen a few Android devices that block exports, we'll take a look at logs and see if there's a technical reason for this
- For raw data use, please see: https://github.com/clariusdev/signalproc, it will describe how to collect and push to cloud (or you use Cast API to pull raw data)
- Mobile API is a separate purchasable license, it does not allow for collect raw data, just B images

**Comment by clariusk** [comment]
Note, 7.3.4 was released for Android which will fix the export problem.s

**Comment by rBirde** [comment]
Hi Kris,

We are using the most up to date version of the app. The tgc and yml files
contain no valuable information on the tgc curves which is crucial to our
application.

Yours sincerely,
Reza
