### ISSUE TITLE
newImage contains 0 when listening to the newProcessedImageFn callback

### ISSUE THREAD

**Issue by deanzadok** [clariusdev/cast#13]
Dear team,

We are trying to create a simple loop that will read incoming processed images from our L15HD and we took the callbacks examples you posted at https://github.com/clariusdev/cast/blob/master/src/example/caster/main.cpp but we are unable to receive images.

Using the callback newProcessedImageFn, the newImage pointer is an address to a variable containing a single zero. Basically, when using this code as a callback to the processed images and listening to it:
```
/// callback for a new image sent from the scanner
/// @param[in] newImage a pointer to the raw image bits of
/// @param[in] nfo the image properties
/// @param[in] npos the # of positional data points embedded with the frame
/// @param[in] pos the buffer of positional data
void newProcessedImageFn(const void* newImage, const ClariusProcessedImageInfo* nfo, int npos, const ClariusPosInfo* pos)
{
    PRINT << "new image (" << newImage << "): " << nfo->width << " x " << nfo->height << " @ " << nfo->bitsPerPixel
        << "bits. @ " << nfo->micronsPerPixel << " microns per pixel. imu points: " << npos;

    auto image = *(reinterpret_cast<const int*>(newImage));

    if (npos)
        printImuData(npos, pos);
}
```
The variable image contains a single zero.

Can you please tell us what we are doing wrong?

Our machine is a Windows 10 machine, and our project was compiled in visual studio 2019 by donwloading the lib files from releases and including files and directiories in the same way that was suggested in the provided makefile. The machine is connected to the probe using its own Wifi and the callbacks are called expectedly when the capture session begin.

Thanks in advance!
Dean

**Comment by clariusk** [comment]
thanks Dean for your detailed description, can you post a few lines of the exact PRINT output.

**Comment by julien-l** [comment]
When you do:

    auto image = *(reinterpret_cast<const int*>(newImage));

the type of `image` is `int`, it is not an array. This is equivalent to:

    const int* ptr = reinterpret_cast<const int*>(newImage);
    int image = *ptr;

The first byte of the image is likely to be black, that is: `0x0`.

Also note that `int` is probably 4 bytes on your platform, but the image data is 1 byte per pixel (`unsigned char` or `std::uint8_t`).

Example of exporting the array in a file:

    std::string path = std::to_string(nfo->tm) + ".raw";
    std::ofstream ofs(path, std::ios::binary);
    ofs.write(static_cast<const char*>(newImage), nfo->width*nfo->height);
    ofs.close();

**Comment by deanzadok** [comment]
Thank you both for the fast response! and for the detailed explanation!
I understand my mistake. I will modify the code tomorrow according to Julien's suggestion and will update this thread.

**Comment by deanzadok** [comment]
I tried to replace my wrong trial, i.e.:
```
auto image = *(reinterpret_cast<const int*>(newImage));
```
with Julien's suggestion:
```
std::string path = std::to_string(nfo->tm) + ".raw";
std::ofstream ofs(path, std::ios::binary);
ofs.write(static_cast<const char*>(newImage), nfo->width*nfo->height);
ofs.close();
```

And I cannot understand the structure of the stored image. I tried to write it as a text file so I can see the data but I don't understand why is it not just pixel values (i.e., something from 0 to 255) and garbage instead?

I'm attaching examples of the stored data (both raw and txt extensions), can you please tell me what am I doing wrong?

The file size is 307,200 bytes (640x480) so I'm assuming that I have some string conversion problems but I can't find them. Also attaching a print example.

![Capture](https://user-images.githubusercontent.com/18471571/106645941-b9ff9780-6595-11eb-9a15-00b69c36cc81.PNG)

[304319062720.txt](https://github.com/clariusdev/cast/files/5913592/304319062720.txt)

[72415975890.zip](https://github.com/clariusdev/cast/files/5913598/72415975890.zip)

**Comment by clariusk** [comment]
perfect, that's the expected output
i suggest looking at the Qt example, it deals with the image data to run through the pipeline to final display: https://github.com/clariusdev/cast/blob/master/src/example/caster_qt/main.cpp

**Comment by julien-l** [comment]
I noticed I previously gave you an example for the _raw data_ callback. For the processed B-image callback, pixels are encoded in RGBA so the actual buffer size is `width * height * bytes per pixel`:

    std::string path = std::to_string(nfo->tm) + ".raw";
    std::ofstream ofs(path, std::ios::binary);
    ofs.write(reinterpret_cast<const char*>(newImage), nfo->width*nfo->height*nfo->bitsPerPixel/8);
    ofs.close();

> And I cannot understand the structure of the stored image. I tried to write it as a text file so I can see the data but I don't understand why is it not just pixel values (i.e., something from 0 to 255) and garbage instead?

The image is a matrix stored in a C buffer in row-major order. Each element represents a pixel. Each pixel is encoded on N bytes where `N = nfo->bitsPerPixel/8`.

The image is binary data, not text. Try opening the resulting file in `hexdump` to see the pixel values.

**Comment by clariusk** [comment]
you can use Qt to create any type of image format you want from raw data, please look at the code reference i sent previously (specifically the use of QImage), really just 2 lines of code.

image_ = QImage(width, height, QImage::Format_ARGB32);
memcpy(image_.bits(), img, width * height * (bpp / 8));

voila your ultrasound image is ready

https://doc.qt.io/qt-5/qimage.html#save

**Comment by deanzadok** [comment]
Are there any other options rather than using Qt? I can see it is a subscription based and we prefer to use something that is avavilable for free

**Comment by clariusk** [comment]
perhaps, our domain is using C++ and Qt
Qt is free if you aren't commercializing your software

**Comment by deanzadok** [comment]
Thanks to both of your code examples, I was able to translate the bytes memory transfer to an opencv object and it works perfect!

This is how the final callback looks like:
```
/// callback for a new image sent from the scanner
/// @param[in] newImage a pointer to the raw image bits of
/// @param[in] nfo the image properties
/// @param[in] npos the # of positional data points embedded with the frame
/// @param[in] pos the buffer of positional data
void newProcessedImageFn(const void* newImage, const ClariusProcessedImageInfo* nfo, int npos, const ClariusPosInfo* pos)
{
    PRINT << "new image (" << newImage << "): " << nfo->width << " x " << nfo->height << " @ " << nfo->bitsPerPixel
        << "bits. @ " << nfo->micronsPerPixel << " microns per pixel. imu points: " << npos;

    // save image using OpenCV
    cv::Mat mat = cv::Mat(nfo->height, nfo->width, CV_8UC4, (void*)newImage);
    ushort* data_start= mat.ptr<ushort>();
    memcpy(data_start, newImage, nfo->height * nfo->width * 4);
    cv::imwrite(std::to_string(nfo->tm) + ".jpg", mat);
}
```

I can share the final code examples later if needed. Here is an image example:
![370571100700](https://user-images.githubusercontent.com/18471571/106941708-daf9f100-672b-11eb-87d3-6bd83bfaf2bf.jpg)

Kris and Julien, thank you both for you time!!

**Comment by clariusk** [comment]
ahh, thanks for the confirmation! yes opencv is a good tool to get the images as well, we just don't work with that library typically.

**Comment by avexnsx** [comment]
@deanzadok could you please share the code example? Thank you!
