### ISSUE TITLE
Capture Image and Accessing images from UltrasoundImage object

### ISSUE THREAD

**Issue by lydiazoghbi** [clariusdev/cast#131]
Hello! I'm not sure if the "Capture Image" button in caster_qt is doing anything (unless I'm misunderstanding its purpose). Any hints on where it's storing any captured images and the naming convention?

On another note, I'd like to write my own function for saving the US images, but I'm not sure how to access them from the UltrasoundImage object. Any way I can see the public members of UltrasoundImage? 

Lastly, the iOS app is on version 10.3, so when I downloaded the cast binaries for 10.4, I got a version mismatch error, so had to use your 10.3 binaries. Is this expected behavior?

**Comment by clariusk** [comment]
- the capture image function triggers a capture within the Clarius App, so it should be contained in the App's current exam
- which platform are you running on, we can document more the image object if needed?
- yes, versions must match

**Comment by lydiazoghbi** [comment]
- Ah, my bad, I was assuming it will save the image on my system.
- Ubuntu 22.04
- What are the 10.4 binaries released for? Or that's in anticipation of the company releasing the iOS app soon-ish?

**Comment by julien-l** [comment]
10.4.0 was released in pilot version (not available on app stores), instructions to join the pilot program: https://support.clarius.com/hc/en-us/articles/360019548852-Joining-the-Pilot-Program

**Comment by clariusk** [comment]
UltrasoundImage has a QImage member called image_, you can call the save() function (see the Qt API) to store the image.
