### ISSUE TITLE
Using PC to set the settings

### ISSUE THREAD

**Issue by AliKafaei** [clariusdev/cast#133]
Hi,
We need to set the settings of Calrius using PC instead of using the phone app and manually change the settings like gain, depth, etc. Our main motivation is that by doing this, the image collected from all patients would have similar settings. Is there any way to do that ?
Can we have pre-setup settings instead of PC so we load that setup (like imaging modes)?

**Comment by clariusk** [comment]
see https://github.com/clariusdev/cast/blob/master/include/cast/cast_def.h, the CusUserFunction enum gives a set of commands you can send
