### ISSUE TITLE
Transmit M-Mode video data to python programm with cast api

### ISSUE THREAD

**Issue by Contused** [clariusdev/cast#134]
In our research project we try to display the ultrasound video together with the m-mode from the clarius (c3 hd3) probe. We can't find any option to get the m-mode data. The function newProcessedImage only transmits the ultrasound images without the m-mode images.

Is there a way to transmit the m-mode video data corresponding to the ultrasound video received by newProcessedImage?

**Comment by clariusk** [comment]
yes, check out the newSpectralImage callback

**Comment by Contused** [comment]
Yes that works. Thank you very much!
