### ISSUE TITLE
Missing pyclariuscast.pyd for Python 3.10 in 11.0 windows binaries ZIP

### ISSUE THREAD

**Issue by Contused** [clariusdev/cast#139]
Hi,

I tried upgrading our software to the latest version and noticed that there is no folder for the Python 3.10 pyclariuscast.pyd in the 11.0 windows binaries ZIP. Can I use the pyd from another Interpreter Version or binary ZIP? Or will there be an update to the windows binaries?

**Comment by julien-l** [comment]
Hi thanks for reporting, there was an issue in our builder, I will update the release before the end of this week with the missing binaries.

**Comment by julien-l** [comment]
Just fixed now, I updated the Windows artifact in https://github.com/clariusdev/cast/releases/tag/v11.0.0 to include the missing python 3.10 binary. I will close this issue, don't hesitate to re-open it if there is still an issue.
