### ISSUE TITLE
API not connecting to computer

### ISSUE THREAD

**Issue by caseyPT23** [clariusdev/cast#14]
Hello a colleague of mine (Darren Lund) has been working with [redacted] regarding a Clarius US project. If [redacted] is available please have them contact me? I am needing a specific Clarius IP address and port in order to allow an API connection to work.

I have tried the IP listed on the screen when using the Clarius probe.  

I have copies of terminal coding used to help troubleshoot.

Thank you,

-Casey

**Comment by clariusk** [comment]
Please post your platform, the program you're running, and the error messages you're receiving.

**Comment by julien-l** [comment]
Hi Casey you should be able to see the IP and port in the Clarius app once connected to the scanner (I ensured your scanner has the appropriate research license to use the cast API).

Note that the Clarius app must be running and connected to the scanner before you can start casting images to your computer. Also make sure your computer is on the same network as the probe.

![Screenshot_20210203-115438](https://user-images.githubusercontent.com/1530763/106802125-5d44c100-6617-11eb-9429-d1dcff5b9207.png)

**Comment by caseyPT23** [comment]
Thank you.  Please see attached platform screen shots from our last attempt to connect.  

Yes tried the IP and casting port listed on the app.  Even tried IP of smart tablet connected to scanner and of computer.  Computer, smart table and scanner were connected to the same network.  

Please understand this is not my specialty.  Darren has asked me to correspond since it is my computer we are attempting to connect. 

<img width="1156" alt="Screen Shot 2021-01-30 at 8 44 29 AM" src="https://user-images.githubusercontent.com/78495533/106876454-b65b3600-66a5-11eb-9f46-d6808b00bc80.png">
<img width="941" alt="Screen Shot 2021-01-30 at 8 44 54 AM" src="https://user-images.githubusercontent.com/78495533/106876463-b824f980-66a5-11eb-81b7-eaaec2d2596d.png">
<img width="425" alt="Screen Shot 2021-01-30 at 8 45 09 AM" src="https://user-images.githubusercontent.com/78495533/106876475-bc511700-66a5-11eb-9af8-f77986c14d23.png">
<img width="342" alt="Screen Shot 2021-01-30 at 8 45 22 AM" src="https://user-images.githubusercontent.com/78495533/106876483-be1ada80-66a5-11eb-9083-04f46485d830.png">
<img width="360" alt="Screen Shot 2021-01-30 at 8 45 31 AM" src="https://user-images.githubusercontent.com/78495533/106876492-c1ae6180-66a5-11eb-95b4-b2020bbd2956.png">
<img width="575" alt="Screen Shot 2021-01-30 at 8 45 44 AM" src="https://user-images.githubusercontent.com/78495533/106876498-c3782500-66a5-11eb-9c7e-9d0b28a2b64b.png">
<img width="1153" alt="Screen Shot 2021-01-30 at 8 45 56 AM" src="https://user-images.githubusercontent.com/78495533/106876509-c541e880-66a5-11eb-89dc-180b76a504bb.png">
<img width="1158" alt="Screen Shot 2021-01-30 at 8 46 11 AM" src="https://user-images.githubusercontent.com/78495533/106876523-c7a44280-66a5-11eb-83c3-83b02dbbf661.png">

**Comment by clariusk** [comment]
please ensure you're on the scanner's wifi network

**Comment by caseyPT23** [comment]
Hi Julien,
Believe we have the right process for connecting and getting the API running, but am having trouble connecting the probe wifi to the computer.  This has even failed when attempting to share the probe wifi network password from one apple device to another.  Also tried connecting using the probe password.  Any suggestions?

**Comment by clariusk** [comment]
You may want to use the option to have the probe running on your local network, that way you don't have to worry about the probe's hotspot and getting your PC on it, you can find instructions here: https://support.clarius.com/hc/en-us/articles/360019514951-Connecting-to-the-Scanner-via-a-Local-Wi-Fi-Network

**Comment by caseyPT23** [comment]
This is still not connecting.  Is someone available for a video chat on Wednesday 2/17?

**Comment by clariusk** [comment]
sure, send a message to support@clarius.com, and someone will arrange a call with you
