### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by Brian-DeFlaminio** [clariusdev/cast#140]
I have been having quite a bit of trouble getting the code to compile, usually the issue is Boost Library dependencies not being met but I'm sure I'm missing something else too. If you could provide/point to a more in-depth tutorial for how to get all of the required libraries to behave that would be great (every boost installation is different and none have worked for me, and the program can't compile without the threads library provided by boost).

Also the "*.pro" file that QT developer should be able to open refuses to open the project properly and there are no kits available for it. (Should I have a specific version of QT dev?)
![Capture](https://github.com/clariusdev/cast/assets/101814985/ce19b9c0-be3f-4998-b4a6-3ccbed65bd1d)

**Comment by julien-l** [comment]
Boost: ensure Boost headers are in the "include" path of your compiler, if using MSVC, you can edit the %INCLUDE% environment variable to add the Boost include directory. In the case of the `caster` example, Boost is only used on Windows to parse command line arguments, if you don't need them, you can safely remove all code using Boost.

Qt: try Qt 6.5.2. Not sure why your kits are not suitable without more details (do you have error messages from the Qt Creator console?)

**Comment by Brian-DeFlaminio** [comment]
![image](https://github.com/clariusdev/cast/assets/101814985/894d01c5-fde7-4407-b6eb-7d5df9ba4a84)
![image](https://github.com/clariusdev/cast/assets/101814985/9dd3b84d-f19b-43de-ac9c-834eabab48c4)

 This is how I have it set up currently, do I have it in the wrong place?

If I was to just excise the code with errors I would getting rid of parts of main which I was concerned about doing outright.
/// main entry point
/// @param[in] argc # of program arguments
/// @param[in] argv list of arguments
int main(int argc, char* argv[])
{
    int rcode = init(argc, argv);

    if (rcode == CUS_SUCCESS)
    {
        std::atomic_bool quitFlag(false);
        std::thread eventLoop(processEventLoop, std::ref(quitFlag)); //Right here keeps failing, thread not a member of stdlib
        eventLoop.join();
    }

    cusCastDestroy();
    return rcode;
}

**Comment by clariusk** [comment]
You may want to forego using boost code and parse command line manually: https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170

We included boost since the standard C library for parsing command line arguments is not included in Windows, but it's not mandatory, and manually parsing or hardcoding values will do just fine.

**Comment by Brian-DeFlaminio** [comment]
Even when I comment out boost library parts of the code I'm getting the following series of errors, I am using version 11.0.0 too. Do you have a copy of the code with no boost library elements for me to test? 
![image](https://github.com/clariusdev/cast/assets/101814985/7ce600f4-1def-4041-837a-50f2cb1a8235)

Also the QT project file within the cast-11.0.0 folder is all I've been able to open in QT design studio, and it seems without a suitable kit I can't progress and there are no real errors to be seen. (Granted I've never used it before so I'm sure I am missing something on my end.) This is all that opens for me in QT design studio. 
![image](https://github.com/clariusdev/cast/assets/101814985/ce35251b-68bb-4cb2-969d-385e109ddff5)

**Comment by Brian-DeFlaminio** [comment]
What QT Creator Kit was used to compile the project? I currently have it running MinGW for the C and C++ code but am running into errors that I can't decipher. The default kits had many errors that I believe was the fault of a C++ compiler trying to run C, so I made a kit with the following settings: 
![image](https://github.com/clariusdev/cast/assets/101814985/c7a29334-fc2b-4b62-a379-b53e379ab224)
It then gives me the following 3 errors 
![image](https://github.com/clariusdev/cast/assets/101814985/2762ec20-d1b3-46af-8e52-0ebc98a03857)

**Comment by julien-l** [comment]
`ld` is the linker, apparently it cannot find the cast library, ensure you have placed `cast.lib` into the library folder indicated in the `.pro` file (in variable `LIBPATH`).

**Comment by Brian-DeFlaminio** [comment]
Adding the cast.lib file to the include folder within cast worked. The lib file wasn't initially included in the cast-11.0.0 download though, maybe add a note to the readme?
