### ISSUE TITLE
Scan Conversion

### ISSUE THREAD

**Issue by mahbangj** [clariusdev/cast#141]
Hi!

I wanted to know whether anyone has scan conversion codes for the Clarius probes. I want to reconstruct the image and need to do a scan conversion so it will follow the shape of the probe.

**Comment by clariusk** [comment]
sorry, we do not provide scan conversion code, there are some examples in Matlab, and possibly other languages: https://github.com/wme7/Aero-matlab/blob/master/K-wave/k-Wave/scanConversion.m
