### ISSUE TITLE
Failed to connect to the scanner with 11.0.0

### ISSUE THREAD

**Issue by answerrtx** [clariusdev/cast#143]
Hello, I am using the latest release of castAPI (11.0.0), with windows 11 and Qt 6.5, and the firewall was disabled.

When I try to connect the caster-qt example, it throws an error:

connect failure: Exception ocurred (Invalid message response for command get multicast (0); contains 0 sub-packets rather than 2))

And I noticed that the SW Revision is Mismatch

The version of mobile app is 11.0.0-6316+bf1bbd364b, the scanner software version is 11.0.0-540+bf1bbd364b, the image can be streamed to the Clarius app.

Do you know how to solve it? 

Thank you!

**Comment by julien-l** [comment]
It seems the probe's firmware itself has not been updated, start the app, attempt to connect to probe and you should get a prompt to upgrade the probe's firmware -> accept and once the upgrade is complete, try the cast example again.

**Comment by answerrtx** [comment]
> It seems the probe's firmware itself has not been updated, start the app, attempt to connect to probe and you should get a prompt to upgrade the probe's firmware -> accept and once the upgrade is complete, try the cast example again.

Thank you! It works now.

BTW, I found this example should run Clarius on the moblie app to open Wi-Fi, is it possible to create a Windows desktop app that directly connects to the scanner?

**Comment by clariusk** [comment]
Yes Cast also supports Windows, you can find example code in this repository and binaries in the release

**Comment by answerrtx** [comment]
> Yes Cast also supports Windows, you can find example code in this repository and binaries in the release

I believed there are some example codes in previous versions to call the bluetooth, but they're removed from the current version. Does it mean we should implement the bluetooth call up function by ourselves?

Thanks,

**Comment by clariusk** [comment]
This is just in the Solum API which is for OEM customers and requires a different business arrangement with Clarius

**Comment by answerrtx** [comment]
> This is just in the Solum API which is for OEM customers and requires a different business arrangement with Clarius

Got it, thank you!
