### ISSUE TITLE
Problems building Clarius APIs

### ISSUE THREAD

**Issue by stkatharina** [clariusdev/cast#144]
Dear Clarius Team, 
I have problems building the Clarius APIs under Python in Visual Studio. I have followed issue #9 but cannot find instructions on how to install the Clarius pycast https://github.com/clariusdev/cast/tree/master/src/python as the link does not work. I also cannot build the file tree structure as instructed: "Then extract the archive and place the library files in the location that is expected by the Makefile, in cast/src/lib".  Please provide me with instructions on how to build the APIs.
Thank you!

**Comment by clariusk** [comment]
hi there, we do not provide specific build instructions for IDEs like Visual Studio as there are so many options to support, we rely on programmers to understand the build systems they are working on.

For python, you should not have to build anything, but run "python pycaster.py" for example. The readme explains a very generic way under Linux to accomplish this, the steps would be similar under Windows, where you would need the pyd and dll files to exist in the same directory or system path. Note there are 4 versions of Python supported in our builds - 3.8 through 3.11
