### ISSUE TITLE
documentation cast api 11

### ISSUE THREAD

**Issue by virgileMaon** [clariusdev/cast#147]
Good morning
I can't find the documentation for cast api 11.
I'm looking to retrieve battery and temperature information.

in advance thanks.

**Comment by julien-l** [comment]
Hello, this information is not sent over the cast library. This library aims to remain simple and focuses on imaging data.

You could try to read this info over Bluetooth, the specifications are here: https://github.com/clariusdev/solum/blob/master/specifications.md#connectivity.

**Comment by virgileMaon** [comment]
Thank you.

So the last documentation is 
[https://clariusdev.github.io/cast/reference/android/10.4.0/me/clarius/sdk/package-summary.html](https://clariusdev.github.io/cast/reference/android/10.4.0/me/clarius/sdk/package-summary.html)
?

**Comment by julien-l** [comment]
The latest Javadoc should be 11.0.0, it is an omission, I will upload it soon.

**Comment by julien-l** [comment]
Hi, I uploaded the Javadoc for [11.0.0](https://clariusdev.github.io/cast/reference/android/11.0.0/me/clarius/sdk/package-summary.html) and [11.1.0](https://clariusdev.github.io/cast/reference/android/11.1.0/me/clarius/sdk/package-summary.html).
