### ISSUE TITLE
Black backgroud with no image casting

### ISSUE THREAD

**Issue by PedroMatos14** [clariusdev/cast#15]
I am having an issue with the example program in which I can open the application, connect to the clarius via wifi direct and use the buttons with success but the image from the ultrasound does not appear in the main screen with it just showing the black background. I have made no alterations to the code so I don´t really know why this is happening, any ideas?  Thanks

-Pedro

**Comment by clariusk** [comment]
If you're on Windows, double check your firewall settings, a port may be blocked

**Comment by PedroMatos14** [comment]
Thank you for the quick responde, I just checked and apparently the port is not blocked, any other suggestion?
![port not blocked](https://user-images.githubusercontent.com/63508025/109983153-dad91b00-7d02-11eb-83d4-a5a9825fbafe.PNG)

**Comment by clariusk** [comment]
To confirm, tcp connection is ok, and you can get status messages through the cast program?

**Comment by PedroMatos14** [comment]
The connection is successful and the buttons 'Freeze'/'Run', 'Shallower', 'deeper' are working perfectly. Strangely there is just no casting image.
![gui print](https://user-images.githubusercontent.com/63508025/109986450-0a3d5700-7d06-11eb-9b21-ba63a1d65ef2.PNG)

**Comment by clariusk** [comment]
It's likely the UDP port being blocked still. You could try completely disabling firewall temporarily and see if that helps

**Comment by PedroMatos14** [comment]
I completely disabled my windows firewall and it still didn't work.

**Comment by PedroMatos14** [comment]
[Update] - I tried on Linux and it worked so I guess I'll use it from now on

**Comment by clariusk** [comment]
thanks, I was testing again on Windows, and ran into the same issue. Turning completely off the Windows Defender solved it, but so should adding a blanket port exception for the program.

**Comment by tjkarrett** [comment]
I'm having this exact same issue running on a Ubuntu VM on Windows, even after disabling Windows defender entirely. Any ideas?

**Comment by PedroMatos14** [comment]
For me it only worked when I disabled windows Defender and then restarted my pc.

**Comment by tjkarrett** [comment]
> For me it only worked when I disabled windows Defender and then restarted my pc.

Thanks for the idea. I tried it and unfortunately it didn't work. Maybe because of the VM, but I'm not sure.

**Comment by julien-l** [comment]
We have not tested the Cast API in containers, but generally make sure the hosted system (Ubuntu in your case) has transparent access to the host network (Windows). For example in Docker, try the `host` network type:

> host: For standalone containers, remove network isolation between the container and the Docker host, and use the host’s networking directly. See use the host network.

**Comment by tjkarrett** [comment]
Thanks. I decided to just run it in a natively in Ubuntu and it seems to be working without issue, so I assume Windows was blocking it somehow.
