### ISSUE TITLE
How to check whether my probe has Cast API license

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#152]
Hi Clarius Team,

I use Clarius Mobile App to connect to my probe. The connection was done successfully but it didn't show IP/port of for cast. I have no idea if it is software problem or the Cast API license has been expired.

I checked the app's settings, scanner status and my cloud.clarius.com but couldn't find any information about it.

Are there anyway to check what programming licenses (Cast API, Solum, etc) my probe has?

Thank you.

**Comment by clariusk** [comment]
if you contact support@clarius.com they can help you figure out licensing for a device, thanks

**Comment by nguyenvuduc** [comment]
Thank Kris
