### ISSUE TITLE
Probably a version mismatch? Caster Boost.Python.ArgumentError: did not match C++ signature:

### ISSUE THREAD

**Issue by aris-t** [clariusdev/cast#153]
I suspect this is a version mismatch between python and the C++ library though not sure. May be simpler.  

Issue:
```
python3 pysidecaster.py 
Traceback (most recent call last):
  File "/home/aris/Desktop/4Dan/KEWL/cast/examples/python/pysidecaster.py", line 376, in <module>
    main()
  File "/home/aris/Desktop/4Dan/KEWL/cast/examples/python/pysidecaster.py", line 367, in main
    cast = pyclariuscast.Caster(newProcessedImage, newRawImage, newSpectrumImage, newImuData, freezeFn, buttonsFn)
Boost.Python.ArgumentError: Python argument types in
    Caster.__init__(Caster, function, function, function, function, function, function)
did not match C++ signature:
    __init__(_object*, _object*, _object*, _object*, _object*, _object*)
```

Version Information:
```
python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

```

Used pyclariuscast.so from [cast-11.0.0-linux.x86_64-gcc_ubuntu_22.04](https://github.com/clariusdev/cast/releases) / python310 /

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

Any help is appreciated.

**Comment by aris-t** [comment]
Ok, not a fix but a workaround,
It looks like the latest version of examples on master has issues with Boost not managing the signatures and types correctly. All that is beyond me as a humble python idiot. That said there is a workaround. 

Switch to branch [/examples/v11.0.0](https://github.com/clariusdev/cast/tree/examples/v11.0.0)

Worked like a charm.

**Comment by julien-l** [comment]
Hi--a new parameter was added to `pyclariuscast.Caster()` in version 11.1.0 to handle IMU data, which now accepts 6 parameters versus 5 for version 11.0.0, hence the error. Simply remove the `newImuData` parameter from the constructor (or revert the code to the git tag v11.0.0 like you did).
