### ISSUE TITLE
Requesting raw data problem

### ISSUE THREAD

**Issue by PedroMatos14** [clariusdev/cast#16]
Sorry to disturb, this is probably something really obvious that I am not seeing but when using the caster_qt example program, as I freeze the image and click on the request button, all I get is the message stating "No raw data currently buffered" and I can not seem to understand why. Is there something I should do prior to clicking on that button?

**Comment by clariusk** [comment]
for collecting raw data, you must first ensure you use the Clarius App to engage the raw data capture.

**Comment by PedroMatos14** [comment]
Are you saying that I need to click on the photo icon present in the Clarius App to take a photo and then I should click on the request button to be able to download that photo? I am doing this and still it puts foward the same message

**Comment by clariusk** [comment]
you can read more on raw data acquisition here: https://github.com/clariusdev/signalproc
