### ISSUE TITLE
About low-level parameters control

### ISSUE THREAD

**Issue by noseefood** [clariusdev/cast#163]
Hi, I am a researcher using Clarius. Thank you for your genius product. But I have a problem:
In another repo, "clariusdev/raw" 's README file, it seems we could control some low-level parameters such as "steer angle", but in cast API Python's example and **cast_def.h** file, I could not find the possible interface for "steer angle".  
So, I want to know if a Python-based method can control these low-level parameters and, if so, how to enable them.
Thank you very much for your help.

**Comment by clariusk** [comment]
from cast.h, you would use:

cusCastSetParameter()
cusCastEnableParameter()
cusCastSetPulse()

to set low level parameters as documented in the raw repository

the corresponding functions exist in the python wrapper as well
