### ISSUE TITLE
Python examples in Windows

### ISSUE THREAD

**Issue by rorybennett** [clariusdev/cast#167]
**Description**
Example python scripts do not run in Windows, process exits with the following error:
_import pyclariuscast
ModuleNotFoundError: No module named 'pyclariuscast'_
I cannot find this pyclariuscast module.

What has been tried:
- Run from within an IDE (Python3.11 through PyCharm) and from the terminal (Python3.10 through PowerShell).
- I followed issue #145 and have included the .lib and .dll files in the same folder as the scripts.

**To Reproduce**
1. Download cast-11.2.0-windows.x64 release.
2. Download cast-master.
3. Copy cast.dll and cast. lib from the Windows release into the examples/python directory.
4. Run pysidecaster.py/pycaster.py/pyimu.py script, either in an IDE or from the terminal.
5. Error is displayed.

**Environment:**
- SDK variant [e.g. python wrappers, iOS Framework]: Python scripts.
- Development platform [e.g. Linux, Xcode]: Windows 11.
- SDK version: 11.2.0
- Clarius App version: NA

**Other**

- I have attempted to run the Linux version with no luck either using WSL and various python versions. The scripts cannot locate the libcast.so and pyclariuscast.so files even once they have been moved into the same directory as the python script. This is not my main concern, as I would prefer to have this running in Windows.
- It is possible that I may just not know how to use .dll files. If there is a specific resource I need to use to get the example python scripts running in Windows could that please be supplied?
- It is mentioned in the examples/python README.md that the `pyclariuscast` wrapper has been made to make this process easier. Where is this wrapper?

**Comment by julien-l** [comment]
Hi thanks for reporting it seems some files are missing in the released archives, we will look at it.

**Comment by rorybennett** [comment]
Thanks!

**Comment by keerthivasan1901104** [comment]
Is this fixed ?

**Comment by rorybennett** [comment]
It does not look like it. The last commit in the python examples is still from 5 months ago.

**Comment by julien-l** [comment]
Hi we have updated the Windows asset for Clarius Cast v11.2.0 here, it now contains the missing python libraries `pyclariuscast.pyd`. You can download it here: https://github.com/clariusdev/cast/releases/download/v11.2.0/cast-11.2.0-windows.x86_64.zip.

Let me know if this works for you, thanks for your patience.

**Comment by rorybennett** [comment]
Things seem fine now, thanks a bunch!

**Comment by julien-l** [comment]
Good then I will close the ticket, don't hesitate to re-open it if needed. Thanks again for reporting the issue!
