### ISSUE TITLE
iOS / Catalyst / arm64 Support

### ISSUE THREAD

**Issue by wilmarvh** [clariusdev/cast#18]
Hi

I'm interested in deploying the cast API on an iOS device as part of a 3rd party application, however I don't see iOS listed as a supported platform:

- Is iOS supported available, but undocumented perhaps?
- If supported is there any references/examples available?
- If not supported, is it planned for the future, and is there perhaps a timeline?

Regards
Wilmar

**Comment by clariusk** [comment]
Currently, there are no plans to support mobile platforms for the Cast API.

**Comment by wilmarvh** [comment]
Thanks @clariusk. Is there a way to file it as a feature request with the development team?

**Comment by wilmarvh** [comment]
@clariusk Follow-up, can you predict how a Mac Catalyst app would work with the castapi? My best guess is that since iOS support isn't available a Catalyst app won't work either?

**Comment by wilmarvh** [comment]
@clariusk I built a small macOS app using SwiftUI, integrating libcast.dylib. The lib doesn't support arm64 however, do you have this on the roadmap? Apple Silicon chips (M1n and likely following generations) requires this architecture for the lib to be deployed on macOS.

**Comment by clariusk** [comment]
we don't have any roadmap for future arm platforms on macOS, but i'll keep tabs on it with the dev team
