### ISSUE TITLE
Example fails to build on Ubuntu 18.04 due to missing dependencies

### ISSUE THREAD

**Issue by tbjoern** [clariusdev/cast#19]
Hello everyone!

After upgrading to v8.0.1, the caster example (`src/example/caster`) fails to build on Ubuntu 18.04 LTS.
This is because `libcast.so` requires `libmysqlclient.so.21` and some other dependencies, that it did not require previously.
The build fails with a linker error:
```
/usr/bin/ld: warning: libmysqlclient.so.21, needed by ../../../vendor/clarius/lib/libcast.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libodbc.so.2, needed by ../../../vendor/clarius/lib/libcast.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpq.so.5, needed by ../../../vendor/clarius/lib/libcast.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsybdb.so.5, needed by ../../../vendor/clarius/lib/libcast.so, not found (try using -rpath or -rpath-link)
```
The mysql shared library is provided by [this package](https://ubuntu.pkgs.org/20.04/ubuntu-main-arm64/libmysqlclient21_8.0.19-0ubuntu5_arm64.deb.html) which is only available on Ubuntu 20.04.

I am curious why this dependency is required now. Was this done intentionally?
The mysql requirement is not documented anywhere.

I also noticed that the binary size of `libcast.so` increased from ~90MB to ~210MB.

Our entire dev team is using Ubuntu 18.04 at the moment, it would be very helpful if upgrading was not required.

Thanks in advance!

**Comment by clariusk** [comment]
We've updated the Mobile API release packages to include the APK files as well, should you want to stick to a previous release.

For dependencies, we use Qt, and often upgrades bring many new items from those libraries in. we also like to stick to the latest LTS for builders, hence 20.04.

**Comment by smistad** [comment]
Hi @clariusk 

I am also very concerned with this new development. libcast.so has 132 dependencies! This is extreme (I have actually never seen a library with that many dependencies before) and makes it very difficult to use in a professional software development, and is a license nightmare. We are also mainly still using 18.04 LTS. Changing main OS every second year can be quite counterproductive.

In short, this makes it difficult for us to use this library on Ubuntu, and I doubt I will be able to use clarius cast with FAST on Ubuntu after this. While the previous version was working perfectly with 18.04 and with only 37 dependencies.
Thus I really hope you will reconsider this and go through your dependencies and reduce it considerably.
For example, do you really need both mysql and sqlite3, they serve the same purpose; providing an SQL database. Do you really need all those sound codecs.. FLAC, ogg, vorbis, pulse .... Do you really need all those image compression formats: jpeg, jbig, lzma, zlib, png. Do you really need both GL and GL ES? I can't possibly think of a reason why. And then there is the 80+ other dependencies which I don't even recognize.

An alternative might be to create a "light" version of your libcast.so, which provides the same functionality as the previous version and thus with a reduced dependency list.

Regards,
Erik

**Comment by julien-l** [comment]
Hi Erik, sorry for the late answer. Agreed the large size of the library is an issue and we will look into reducing it. Thanks for reporting--Julien

**Comment by clariusk** [comment]
binaries should be smaller now in 8.6.0, we still have our build system installed with Ubuntu 20.04

**Comment by smistad** [comment]
Thank you for reducing the binary size
