### ISSUE TITLE
cast.lib has no function signature for cusCastProbeInfo()

### ISSUE THREAD

**Issue by mohankumar90** [clariusdev/cast#20]
Release 8.0.1 cast.lib has no function signature for cusCastProbeInfo(). When I try to use it on windows, it throws error **unresolved token (0A0007B1) "extern "C" int __cdecl cusCastProbeInfo(struct _ClariusProbeInfo *)"**

**Comment by clariusk** [comment]
thanks! we will fix this in the next version

**Comment by clariusk** [comment]
8.3.0 releasing with fix soon.
