### ISSUE TITLE
Could not connect to scanner

### ISSUE THREAD

**Issue by lydiazoghbi** [clariusdev/cast#21]
Hi! I am having the same issue, using a wireless Clarius C3, Ubuntu 18, software version 7.1.0 for listener API. I have the Listener API software license for the probe (though I don't recollect activating anything, just connected to the mobile app). All devices are on the probe's wifi, TCP connection established with the probe, but every time I get a message "could not connect to scanner". I was wondering what resolved the issue for @olim0. Thanks!

_Originally posted by @lydiazoghbi in https://github.com/clariusdev/cast/issues/5#issuecomment-863454950_

**Comment by clariusk** [comment]
the listen api is now the cast api, we suggest using the latest app software (v8 now), though we still support v7 apk's via the mobile api repository.

if your device if licensed accordingly, you will see the ip and port displayed at the top of the screen, use those parameters to connect via the api.
