### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by MarcoTripoli** [clariusdev/cast#22]
Hello,

Using the cast project (latest version) on linux using Qt I noticed that by connecting the ultrasound probe the IMU sensors (accelerometer, gyroscope, magnetometer) are not displayed or printed. Also checking the code I found no parts of code that mention it.

I was wondering in which project files or libraries their values were received.

Thanks in advance

**Comment by clariusk** [comment]
yes, you'll need ensure you enable the sensors via the Clarius App, instructions can be found here: https://github.com/clariusdev/motion

**Comment by MarcoTripoli** [comment]
Hello,
yes, the sensors have been activated via the app, but once the program is started as shown below, the sensor values are not displayed.

![image](https://user-images.githubusercontent.com/37769871/125267192-dce16500-e306-11eb-8464-f8163a35a836.png)


In fact, I was wondering in the Qt Cast code where these values were treated, because I couldn't find them. In the windows project the variables imu, gyro, accel and magnet are used, but I have not found anything similar in the cast of Qt.


Thanks in advance

**Comment by julien-l** [comment]
The Qt example does not make use of the positional data. The Qt example simply ignores it. The positional data is passed to the client in the callbacks `ClariusNewRawImageFn` or `ClariusNewProcessedImageFn`. See here: https://github.com/clariusdev/cast/blob/67a1dd0934e20326522c06aedc38574dbb29f831/src/example/caster_qt/main.cpp#L22

**Comment by MarcoTripoli** [comment]
Thanks for the clarification
