### ISSUE TITLE
IQ to RF data

### ISSUE THREAD

**Issue by AliKafaei** [clariusdev/cast#23]
Hi,
I need to use RF data for a project. The RF data sampling was low so I decided to use IQ data instead. Do you have any code to convert IQ to RF data?
I tried to convert IQ data to RF myself but it seems that some kind of filtering is required since it was noisy.
Regards,
Ali K. Z. Tehrani

**Comment by clariusk** [comment]
sorry, we do not have code to convert IQ to RF
