### ISSUE TITLE
Start time of probe timestamp

### ISSUE THREAD

**Issue by deanzadok** [clariusdev/cast#24]
Dear team,

We are trying to calibrate the timestamps of the received images with a standard unix timestamp (like time.time() in python for example). We realised that the timestamp that is being sent with the image is basically the countdown from when the probe was turned on, but we can't find the time in which the probe was turned on. 

We are referring to this timestamp:
https://github.com/clariusdev/cast/blob/master/src/include/cast/cast_def.h#L56

Is there any way to find the start time of the timestamp of the probe?

Thanks a lot in advance!

**Comment by clariusk** [comment]
as the probe generates the timestamps for the frames, and as it runs an embedded platform and does not care about the time of day, the timestamps are based on a monotonic clock, and hence, there is no way to accomplish what you are asking, only the precise difference between incoming frames. if you want to use your own timestamping method when receiving frames, this would probably serve your purposes better and still be quite precise (ie. < few ms lag)

**Comment by deanzadok** [comment]
Hi Kris, Thank you for your comment and sorry for the delay. After speaking to the support and asking for a feature request, we will wait for their answer. Closing this thread.

**Comment by luohwu** [comment]
Hi Deanzadok,

Is your problem solved? I have the same problem now.
