### ISSUE TITLE
How to activate Waveform button programatically?

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#25]
I am using the Cast API to collect RF data. It seems the Clarius probe only buffers raw data when the mode is RF and the Waveform button is activated. I can use USER_FN_MODE_RF to turn on RF mode, but I couldn't find the code to activate the Waveform button.

**Comment by clariusk** [comment]
there is no function for this, however we now recommend with the new software to save presets to overwrite defaults.
