### ISSUE TITLE
error: connect failure: Exception ocurred (Error connecting to TCP socket: Connection refused)

### ISSUE THREAD

**Issue by smistad** [clariusdev/cast#26]
After the last API update we get the following error message "error: connect failure: Exception ocurred (Error connecting to TCP socket: Connection refused)" using the caster example and our own software. 
We have tried both on windows and ubuntu, and two different scanners/phones, same error message.
Scanner is in "research mode" with port 5858, and the app is up to date.

**Comment by julien-l** [comment]
Hello,
Troubleshooting for the "connect failure" error:
- ensure the scanner's firmware and app version correspond to the SDK version;
- ensure the system that runs the caster application is on the same network as the scanner: in Wi-Fi Direct, connect your system to the scanner's DIRECT network, or use the WLAN connection type.
Julien

**Comment by clariusk** [comment]
note we only have version 8.0.1 fully released, hopefully next month we will have a new version officially released to the stores and we will release our api binaries here as well.

**Comment by smistad** [comment]
We are using the latest release (8.0.1), and the app and firmware is on the same version.
I managed to get it working by selecting "Anyone" in the Clarius Cast setting instead of "Research (5858)". This requires me then do use a random port displayed in the app.
So there seems to be a bug with the fixed port (5858) setting.

**Comment by clariusk** [comment]
yes, sorry, the research option for the casting port got broken, fixed in upcoming released.

**Comment by smistad** [comment]
Okay, thanks

**Comment by clariusk** [comment]
should be fixed in 8.6.0 now

**Comment by smistad** [comment]
I updated to 8.6 in the app, updated the firmware, and the cast API just now on Ubuntu 20.04. 
And I am sorry to say this issue does not seem to be fixed.
If I set Research mode (5858), it says port 5858 in the app, but I get connection refused when trying to connect to this port.
Changing to Anyone cast mode, I am able to connect to the random port specified in the app.

**Comment by slombar** [comment]
I am also having this issue with the newest 9.0 update

**Comment by nalindas9** [comment]
@clariusk I am also having the same issue with the 9.1.0 app update.
