### ISSUE TITLE
USER_FN_SET_DEPTH and USER_FN_SET_GAIN switched

### ISSUE THREAD

**Issue by jnuno420** [clariusdev/cast#27]
Hello

I was trying to increment the depth value with a button using `USER_FN_SET_DEPTH`, and immediately noticed it wasn't increasing or decreasing the depth, then i tried to do the same thing with the `USER_FN_SET_GAIN`, and it affected the depth, so i think these two user function commands are switched.

Another thing, when i try to increase the depth in 2cm using this: `cusCastUserFunction(USER_FN_SET_GAIN, 2, nullptr)` the depth goes to the max, which is 7cm.

The app is up to date and i'm using version 8.0.1

**Comment by julien-l** [comment]
Hi thanks for reporting I will look at it.

**Comment by julien-l** [comment]
I was able to reproduce, it's because the macro definitions for `USER_FN_SET_DEPTH` and `USER_FN_SET_GAIN` are offset by one. We will update the API soon. In the meantime, you can simply fix it by changing the values to:

    #define USER_FN_SET_DEPTH           21
    #define USER_FN_SET_GAIN            22

(Skip the value 20.)
