### ISSUE TITLE
Example fails to run on MacOS 12.0.1 

### ISSUE THREAD

**Issue by jnunomcosta** [clariusdev/cast#32]
Hey,

I'm trying to run the 'caster_qt' example on MacOS 12.0.1, i just downloaded the 8.6.0 version of the library and i'm getting a lot of errors when running the executable. Here's one example:
``
objc[2627]: Class QMacAutoReleasePoolTracker is implemented in both .../QtCore (0x11093e9f8) and .../libcast.dylib (0x11e0a5200). One of the two will be used. Which one is undefined.
``

I'm using CMake to generate the build files and compiling with make.

Is there a quick fix to make it work?

**Comment by clariusk** [comment]
since the cast library links statically with Clarius' version Qt, you may want to ensure that your program links dynamically with Qt.

**Comment by jnuno420** [comment]
Hey, thanks for replying, can you help me do that? 

I've tried researching how to link dynamically and statically with CMake but i couldn't fix it, i'm adding the Clarius Library into CMake with:
`include_directories(${CMAKE_SOURCE_DIR}/lib/include)`
`file(GLOB CLARIUS_LIBRARY "${CMAKE_SOURCE_DIR}/lib/*.dylib")`
...
`target_link_libraries(project Qt5::Widgets ... ${CLARIUS_LIBRARY} )`

Thanks in advance!
