### ISSUE TITLE
How to convert Timestamp field to a regular date format

### ISSUE THREAD

**Issue by jnunomcosta** [clariusdev/cast#34]
Greetings,

I was exploring the timestamp field that the probe provides with each ProcessedImageInfo, however, I got a value like this `45197133150`,  and after searching the internet I couldn't convert it to a date format, the UNIX epoch converter says it's from the year 3402. How can I convert this value into a regular Date format?

Thanks in advance!

**Comment by julien-l** [comment]
Hi these timestamps do not relate to any particular time point like the UNIX epoch, they should be used to compute the time difference between frames. They are generated by a monotonic clock and expressed in nanoseconds.
