### ISSUE TITLE
Clarius Mobile App listen on port 0 when casting

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#35]
The new Clarius Mobile App sometimes listens on port 0. This doesn't make sense as I know port 0 does not exist in TCP/IP protocol. If I use Clarius Cast Api to connect to this port 0, I get an error of "The requested address is not valid in its context".

Environment:
- Mobile Device: iPhone
- Clarius Mobile App: the latest version of today
![image](https://user-images.githubusercontent.com/5864656/142955634-87090de2-64fc-4923-a8a5-b74d10ceaefa.png)

**Comment by julien-l** [comment]
Hi, ensure the cast setting is not set to "disabled". Menu > Settings > Clarius Cast (in advanced settings). Set to "institution" or "anyone".
![IMG_CBE075D75610-1](https://user-images.githubusercontent.com/1530763/142957141-3794617a-018f-4b25-9585-1be57ee6fca9.jpeg)

**Comment by clariusk** [comment]
correct, the clarius cast setting needs to be set, with the Cast license applied to your scanner as well, you'll be see the option for research to set to a static port.
