### ISSUE TITLE
Image not streaming - pycaster.py / pycast.so - linux

### ISSUE THREAD

**Issue by SJackTu** [clariusdev/cast#37]
This issue occurs when testing the v8.6.0 release. 

Environment:
Ubuntu 20.04.3 LTS
Python 3.8.10
Connection - trough an WiFi router without internet connection.

Issue summary:
1. No image streaming, but the app can send freeze state changes to Cast, expected to see the image information being printed when the image is running.
```
(py_venv) :~$ python pycaster.py --address 192.168.100.159 --port 36671
initialization succeeded
connected to 192.168.100.159 on port 36671
press ('q' to quit) ('a' for action): imaging running
imaging frozen
imaging running
imaging frozen
imaging running
imaging frozen
q
```
2. Cast.userFunction could not be send back to the scanner nor app, expected to see 'image frozen / running' being printed after keyboard input.
```
(py_venv) :~$ python pycaster.py --address 192.168.100.159 --port 5828
initialization succeeded
connected to 192.168.100.159 on port 5828
press ('q' to quit) ('a' for action): a
(f)->freeze, (i)->image, (c)->cine, (d/D)->depth, (g/G)->gain: f
press ('q' to quit) ('a' for action): 
(f)->freeze, (i)->image, (c)->cine, (d/D)->depth, (g/G)->gain: f
press ('q' to quit) ('a' for action): a
(f)->freeze, (i)->image, (c)->cine, (d/D)->depth, (g/G)->gain: f
press ('q' to quit) ('a' for action): a
(f)->freeze, (i)->image, (c)->cine, (d/D)->depth, (g/G)->gain: F
press ('q' to quit) ('a' for action): q    
Segmentation fault (core dumped)

```
3. I thought the network are connected, but ping seem ok.
```
(py_venv) :~$ ping 192.168.100.159
PING 192.168.100.159 (192.168.100.159) 56(84) bytes of data.
64 bytes from 192.168.100.159: icmp_seq=1 ttl=64 time=20.3 ms
64 bytes from 192.168.100.159: icmp_seq=2 ttl=64 time=2.55 ms
64 bytes from 192.168.100.159: icmp_seq=3 ttl=64 time=3.75 ms
64 bytes from 192.168.100.159: icmp_seq=4 ttl=64 time=2.57 ms
64 bytes from 192.168.100.159: icmp_seq=5 ttl=64 time=3.88 ms
64 bytes from 192.168.100.159: icmp_seq=6 ttl=64 time=2.53 ms
64 bytes from 192.168.100.159: icmp_seq=7 ttl=64 time=4.06 ms
64 bytes from 192.168.100.159: icmp_seq=8 ttl=64 time=3.29 ms
64 bytes from 192.168.100.159: icmp_seq=9 ttl=64 time=4.02 ms
64 bytes from 192.168.100.159: icmp_seq=10 ttl=64 time=2.80 ms
^C
--- 192.168.100.159 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9013ms
rtt min/avg/max/mdev = 2.526/4.971/20.283/5.138 ms
```

**Comment by clariusk** [comment]
this has the characteristic of a port being blocked due to filtering or a firewall, the result from cusCastConnect is the udp port used for streaming the images.

**Comment by SJackTu** [comment]
Is there any suggestion for checking the filtering or firewall?
v8.0.1 on the same machine and environment did not have this issue.

**Comment by clariusk** [comment]
Each OS is different, but also double check that your app is the latest version

**Comment by SJackTu** [comment]
Thank you.
I have tried my script on the other Linux machine, and data transmission was OK. However, I am still struggling with the same problem on my primary work station.
I deleted all files and re-downloaded the latest release files, and tried the C++ example, and the behave the same, scanner was not connected, but the imaging status changes can go through.
```
:~/Clarius/example/caster$ build/caster -a 192.168.100.159 -p 5828

starting caster...
error: software revisions are different
could not connect to scanner

imaging
frozen
imagingq
Segmentation fault (core dumped)
```
Is this error message to do with Clarius software or the other dependencies?
I also checked the port information, and the result is as follows:
```
COMMAND     PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
caster    11598          ladmin   18u  IPv4 335173      0t0  TCP 192.168.100.146:40632->192.168.100.159:5828 (ESTABLISHED)
caster    11598          ladmin   22u  IPv6 334075      0t0  UDP *:49345 
```
Any suggestion?

**Comment by SJackTu** [comment]
Thank you very much. Problem solved.
I tried the C++ example, which gives an error message about software revision.
I found two instances of libcast.so in my /urs/local/ sub-folders. Issue solved by cleaning all the files and replacing with the latest release.
