### ISSUE TITLE
Position information pointer NULL when receiving 'newProcessedImageFn' events

### ISSUE THREAD

**Issue by philipjpratt** [clariusdev/cast#38]
Is there any extra configuration or settings required to enable positional data (in addition to it being a licensed feature)? At the moment we just seem to get a NULL ClariusPosInfo pointer when the new image events come in via the 'newProcessedImageFn' callback.

**Comment by julien-l** [comment]
Hello, IMU must be activated from the "Mode" menu during scanning, see instructions at: https://github.com/clariusdev/motion.
