### ISSUE TITLE
Failed to stream images from the probe to the PC using the CAST API - when we run the pysidecaster.py

### ISSUE THREAD

**Issue by AlvinKimbowa** [clariusdev/cast#39]
When run the pysidecaster.py in anaconda prompt on a windows 10 machine. The GUI opens, we add the IP address and the port number and then press the “Connect” button. The connection is successful but no image shows up in the image section of the GUI. Only a blank black window is shown.

When we freeze the imaging using the Clarius App on the phone, the status bar in the GUI window indicates “Image Stopped” and when we unfreeze the imaging, the GUI window status bar indicated “Image running”. However, we still don’t see any image being displayed.

Here is the log as seen in the anaconda prompt:
```
(base) C:\Users\xxxx\Desktop\clarius\cast-9.0.0\src\python\python pysidecaster.py
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
WARNING: QApplication was not created in the main() thread.
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
Image Stopped
Image Running
```
Note that we also get warnings about some libraries.

The "python" folder from which we run the pysidecaster.py contains the following files:

- cast.dll
- cast.lib
- pycast.pyd
- pycaster.py
- sidepycaster.py
- README.md

**Comment by julien-l** [comment]
Hello, on Windows systems, the most likely explanation for missing image is blocked network ports. The scanner uses random ports to stream images which might be blocked by Windows. Try de-activating the firewall before running the example.

**Comment by slombar** [comment]
I had this same issue using linux though

**Comment by AlvinKimbowa** [comment]
> I had this same issue using linux though

how did you solve it

**Comment by julien-l** [comment]
In order to isolate the issue (network vs. display), can you try the non-gui python example, you should see log messages as images are received:

```
cast/src/python % python3 pycaster.py -a 192.168.1.1 -p 40555
initialization succeeded
connected to 192.168.1.1 on port 40555
press ('q' to quit) ('a' for action): new image (ps): 101464589720, 384x400 @ 8 bps, 25.67 um/s, 65.00 um/l
new image (sc): 101464589720, 640x480 @ 1228800 bpp, 38.80 um/px, imu: 0 pts
imaging running
new image (ps): 101506080520, 384x400 @ 8 bps, 25.67 um/s, 65.00 um/l
new image (sc): 101506080520, 640x480 @ 1228800 bpp, 38.80 um/px, imu: 0 pts
new image (ps): 101548876330, 384x400 @ 8 bps, 25.67 um/s, 65.00 um/l
new image (sc): 101548876330, 640x480 @ 1228800 bpp, 38.80 um/px, imu: 0 pts
new image (ps): 101590843020, 384x400 @ 8 bps, 25.67 um/s, 65.00 um/l
new image (sc): 101590843020, 640x480 @ 1228800 bpp, 38.80 um/px, imu: 0 pts
```

**Comment by AlvinKimbowa** [comment]
We tried the non-GUI python example pycaster.py. We managed to issue commands to the probe by pressing 'a' and then choosing among the commands such as 'f' for freeze, 'd' for depth and they worked.

However, no log of any new images was seen.

**Comment by AlvinKimbowa** [comment]
> Hello, on Windows systems, the most likely explanation for missing image is blocked network ports. The scanner uses random ports to stream images which might be blocked by Windows. Try de-activating the firewall before running the example.

We tried running the pysidecaster.py after disabling the firewall, but it still couldn't display the images.

However, we are going to try another approach of unblocking all ports for the local network and see if the images will display.

**Comment by AlvinKimbowa** [comment]
We finally resolved the issue by turning off all the firewalls in windows security settings. We managed to stream the images using the pysidecaster.py and also managed to save the images when using pycaster.py.

Thanks a lot @julien-l for your help.
