### ISSUE TITLE
Using CAST API Fails to stream any images when running example code

### ISSUE THREAD

**Issue by slombar** [clariusdev/cast#40]
The CAST API example code does not run properly. I can launch the interface just fine, but as soon as I enter the port number and click connect, no image displays.

**Comment by slombar** [comment]
On a linux machine using the clarius first gen probe

**Comment by julien-l** [comment]
Hello, can you confirm the app is the same version as the Cast API library? They were recently updated to version 9.0.0.

**Comment by slombar** [comment]
Hello, this was with a previous version of this API.  I am trying to get this code to run in QT creator, but the lib files are not recognized, and there are header files that do not exist in cast master.

**Comment by slombar** [comment]
cannot find -lcast is the error i'm receiving from the console

**Comment by slombar** [comment]
And I am attempting on Windows OS.

**Comment by slombar** [comment]
And the library issue comes from this line #include <cast/cast.h>. there is not a cast.h file

**Comment by julien-l** [comment]
The header file is in https://github.com/clariusdev/cast/tree/master/src/include/cast, be sure in include this folder when compiler, e.g. `-I /path/to/include/cast` on g++ or `target_include_directories()` in CMake.

**Comment by slombar** [comment]
Awesome, I included those files and now I have a lot of errors
![image](https://user-images.githubusercontent.com/48625582/151229278-f1ffc167-b68a-4935-85b5-dac757ead2ff.png)

**Comment by julien-l** [comment]
This suggests the `cast.lib` is not passed to the linker. There is a qmake `pro` file that can be used with Qt Creator containing the correct build config. Otherwise look at `target_link_libraries()` for CMake.

**Comment by slombar** [comment]
The .pro file does not have the correct build config, I ran this initially and it did not work or have any header/library files linked properly.

**Comment by slombar** [comment]
Disregard my error before, I needed to add a space onto the LIBS path before -lcast

**Comment by julien-l** [comment]
Download the library here https://github.com/clariusdev/cast/releases for your platform. Unzip it in a `lib` folder inside the `src` folder, next to `include` and `example`:

    .
    ├── LICENSE
    ├── README.md
    ├── blob
    └── src
        ├── example
        ├── include
        ├── lib
        │   ├── libcast.dylib
        │   ├── libcast_plugin.a
        │   └── pycast.so
        └── python

**Comment by slombar** [comment]
How can I add an exception for this program to the windows defender?

**Comment by julien-l** [comment]
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by slombar** [comment]
I just disabled firewall entirely, but I get this error message: Error: connect failure: Exception occurred (Error connecting to TCP socket: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by clariusk** [comment]
ensure you're on the same Wi-Fi network and that IP and port are properly set based on what the App displays.
