### ISSUE TITLE
Software revision are different when use cast 9.0.0

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#41]
Hi Kris,

When I use clarius cast v9.0.0 to connect to the probe with this firmware, I got this error message: "software revision are different"
![image](https://user-images.githubusercontent.com/5864656/152253714-3d4edc38-436f-47fe-a8e6-7c2da90b422f.png)

Do you know what the issue is?

Thank you.

**Comment by clariusk** [comment]
there may have been a mismatch in the binaries uploaded, you can try downloading them again. thanks

**Comment by nguyenvuduc** [comment]
Thank Kris, it works.
