### ISSUE TITLE
ImportError: DLL load failed while importing pycast: The specified module could not be found.

### ISSUE THREAD

**Issue by AlvinKimbowa** [clariusdev/cast#46]
Hello. I am trying to run one of the python examples (pycaster.py) but this error is popping up. I have failed to figure out why I can not import pycast.

I downloaded the binaries at [https://github.com/clariusdev/cast/releases/download/v9.0.0/clarius-cast-v900-windows.zip](url) and the source code at [https://github.com/clariusdev/cast/archive/refs/tags/v9.0.0.zip](url).

I then copied the pycaster.py to the clarius-cast-v900-windwos folder containing the pycast.pyd, cast.lib and cast.dll. When I run the pycaster.py in cmd, that error pops up.

How can I resolve this error?

**Comment by AlvinKimbowa** [comment]
I have figured it out. It turns out this API only compatible with Python 3.8 versions (that is from python 3.8.0 to python 3.8.12). 

It does not work with python 3.9 or python 3.7. 

I have tried those versions on my computer, and python 3.8 worked for me.

**Comment by VijithaP** [comment]
I have got the same error 
DLL load failed while importing pyclariuscast: The specified module could not be found.
Python 3.11.4

**Comment by julien-l** [comment]
Ensure the binaries/DLL are in the correct folder (visible by the python script) and that you use the correct python version. If you still have issues, you can open a new issue with more details: which Cast version do you use, description of the sequence of action etc.
