### ISSUE TITLE
Decoding raw images from callback

### ISSUE THREAD

**Issue by jbcdnr** [clariusdev/cast#50]
Hello,

While recording raw images with this packages we obtain the following images. I can decode most of the images given to the `newRawImage` callback but not the ones of size `192x3904 @ 16 bps`. I added a `>>` to indicate these lines.

```
new image (ps): 142156180010, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142247769280, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142293563900, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142339734730, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142431576530, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142477461140, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142523252870, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
>> new image (ps): 142156180010, 192x3904 @ 16 bps, 38.50 um/s, 300.00 um/l, jpg=0
new image (ps): 142614968510, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142661659870, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142707677580, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142801135130, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142847546990, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 142987705000, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
new image (ps): 143033494720, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
>> new image (ps): 142707677580, 192x3904 @ 16 bps, 38.50 um/s, 300.00 um/l, jpg=0
new image (ps): 143171762080, 192x592 @ 8 bps, 255.28 um/s, 300.00 um/l, jpg=0
```

Naively decoding the bytes as `uint8`, `uint16`, `float16` did not give me good images. I also tried to change the dimension / order of the tensor but it did not help. Any advice? What are these images? Spectrum, envelop or RF? I wondered if it was LZO compressed.

Thank you for your help

**Comment by jbcdnr** [comment]
*More context with the images*

Normal 192x592 images
![139079664490](https://user-images.githubusercontent.com/6209990/159715482-06b6a7d7-d49f-4ead-901e-0d4fdd8035c9.jpg)

The other images
![142156180010](https://user-images.githubusercontent.com/6209990/159715462-373ae82f-b5c9-42f9-bd02-fdcf73668d4f.jpg)

**Comment by clariusk** [comment]
Data coming from the raw data callback is in "raw" format, thus the 8 bit data is greyscale data as you have properly rendered. To get the rendered image, use processed image callback, which will give you data in the geometrically correct format.

The 16 bit data must be the RF signal being streamed, so you must have enabled RF mode from the App. This is 16-bit signed amplitude data, thus you would render the 192 scanlines with each 3904 samples as a radiofrequency signal.
