### ISSUE TITLE
Record information like YAML file with Cast API

### ISSUE THREAD

**Issue by jbcdnr** [clariusdev/cast#51]
Is there a programmatic way with the Cast API to access information contained in the yaml file saved on clarius cloud in raw mode? Like here: https://github.com/clariusdev/raw/blob/master/viewer/data/carotid/carotid_env.yml

```
frame rate: 11 Hz
transmit frequency: 10 MHz
imaging depth: 40 mm
focal depth: 15 mm
tgc: { 0.00mm, 23.00dB }{ 40.00mm, 26.00dB }
size: {samples per line: 784, number of lines: 384, sample size: 1 bytes}
sampling rate: 15 MHz
```

**Comment by clariusk** [comment]
currently no, the API does not give this information, it is just part of the raw data files downloaded from buffering data on the probe  - good OFI for later however, thanks.
