### ISSUE TITLE
Mac M1 release

### ISSUE THREAD

**Issue by jbcdnr** [clariusdev/cast#53]
Hello,

We need a release of the .so and .dylib files compiled for the mac M1 architecture, similarly to `clarius-cast-v910-macos.zip`. Can you provide it?

Thank you.

**Comment by julien-l** [comment]
Hello we are planning to release them but no timeline yet. I expect in a few months.

**Comment by lelouisdeville** [comment]
Hi, 

Would you have an update on mac M1 support and when this will be provided? 

Thanks

**Comment by clariusk** [comment]
no updates yet, we'll have to see what XCode we're using to target the builds

**Comment by mattiaspaul** [comment]
we found a way around the lack of M1 support as follows: run the (py)caster from Clarius in a separate Terminal with Rosetta enabled (and x86_64 version of all libraries/python) and then send the received images as packet data into your own app running on arm64 in a different terminal. Not very elegant but it worked (until the software update happened).
It is certainly possible to build arm64 libraries on Intel-Macs https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary e.g. with Xcode 12+ using `-target arm64-apple-macos11`

**Comment by clariusk** [comment]
@mattiaspaul thanks for providing the workaround, as we deploy more SDK technologies in the future, we'll hopefully have direct M1 support as alluded to above

**Comment by yuanagain** [comment]
<img width="824" alt="Screen Shot 2022-06-27 at 6 46 21 PM" src="https://user-images.githubusercontent.com/6503523/176049360-4699210f-536e-4d56-9973-b641c800a5d7.png">


> we found a way around the lack of M1 support as follows: run the (py)caster from Clarius in a separate Terminal with Rosetta enabled (and x86_64 version of all libraries/python) and then send the received images as packet data into your own app running on arm64 in a different terminal. Not very elegant but it worked (until the software update happened). It is certainly possible to build arm64 libraries on Intel-Macs https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary e.g. with Xcode 12+ using `-target arm64-apple-macos11`

Thank you for the workaround. Did you by chance run into anything like this?
