### ISSUE TITLE
RF data buffer in `newRawImage` has the wrong size

### ISSUE THREAD

**Issue by eclarius** [clariusdev/cast#54]
Hi,

I am trying to work with streamed RF data using the cast API. As stated in the documentation, when using the `newRawImage` callback, every 3 raw images is interleaved with an RF image that has to be interpreted differently (see #50).

Strangely, the buffers I get for those RF "image" are too shorts an don't contain enough bytes to be decoded properly. 

Here is a print of the inputs of my callback for one of those buffer:

```
new image (ps): 449178160930, 48x784 @ 16 bps, 38.50 um/s, 1200.00 um/l, jpg=0
```

With this, we expect the received buffer to have a length of `48x784x2=75264` bytes, however it only has `37632`, so half of it.

Is this an known issue? 

Also note that I also downloaded the same dataset from Clarius Cloud, with which I was able to successfully decode and use the RF data. There really seems to be a mismatch between the data collected with these two methods.

Thanks!

**Comment by eclarius** [comment]
Indeed, we are using the python bindings and there might be a bug in the size of the buffer that is passed from C++ to Python. We added this callback to print infos:

```python
def _print_raw_image_info(image, lines, samples, bps, axial, lateral, timestamp, jpg):
    print(
        f"new image (ps): {timestamp}, {lines}x{samples} @ {bps} bps, buffer size={len(image)} bytes, {axial:.2f} um/s, {lateral:.2f} um/l, jpg={jpg}"
    )
```

Which outputs:
```
new image (ps): 284370834760, 192x400 @ 8 bps, buffer size=76800 bytes, 77.00 um/s, 300.00 um/l, jpg=0
new image (ps): 284428538530, 72x400 @ 16 bps, buffer size=28800 bytes, 38.50 um/s, 800.00 um/l, jpg=0
```

First raw images are fine to decode. For the RF images (second line), it seems that we are missing half of the data: `72 x 400 x 16 / 8 = 57600 bytes = 28800 * 2 bytes`. We are reading the buffer as a `float16` numpy array as follow:

```
arr = np.frombuffer(image, dtype=np.uint8 if bit_per_sample == 8 else np.float16)
arr.shape == (14400,)
```

We try to specify a larger `count` argument to read the missing bytes but it fails. I hope it helps tracking down the problem.

**Comment by clariusk** [comment]
excellent, thanks for tracing that, indeed the buffer was allocated failing to take into account the sample size, so we can correct this for a following release - in the meantime, you would want to use the C program to obtain the proper RF data (greyscale should be fine still using pycast)

**Comment by clariusk** [comment]
@eclarius let me know if you've been able to test the 9.3 software yet - it is now deployed to the stores
others have reported some issues with the python wrapper in 9.3, so curious to see if you are affected in your workflow as well
