### ISSUE TITLE
Raw Data capture

### ISSUE THREAD

**Issue by ashishmittalqure** [clariusdev/cast#57]
Hi,

According to the constraints mentioned in the Readme, 

> Raw data can only be captured while imaging is frozen, except when RF streaming is enabled from the App, in which RF frames are interleaved and streamed over the Cast API when there is a connection

I wanted to know what all data is considered raw data. Is it just IQ and RF signals only? or does raw also include motion data (9-DOF IMU) as well.

I will require the images (B-mode and Doppler) as well as the motion data. Are these available in real time using this API?

Also can you please tell me if the above data (Cartesian images and motion data) will be available real time while using OEM and Mobile API?

I currently do not have the device with me and am looking to acquire it. It would be helpful if you could help with the above query.

Thanks

**Comment by clariusk** [comment]
IMU data can be streamed in real-time (it will also be stored alongside raw data capture bundles). Definition of raw data is greyscale raw (non-cartesian), IQ, and RF.

Processed Color Doppler (separate overlay from B) is also streamed in real-time, the raw Doppler IQ is not.

Mobile API provides cartesian and IMU data in real-time, as does OEM, but we do not support OEM API unless large quantities of systems are purchased.

**Comment by ashishmittalqure** [comment]
Thank you for the prompt response.
