### ISSUE TITLE
Control of Ultrasound probe settings through CAST Application

### ISSUE THREAD

**Issue by ashishmittalqure** [clariusdev/cast#58]
Hi, 

I wanted to know if it is possible to control various probe and imaging setting using CAST API based application.

We our primarily interested in color doppler settings for velocity measurement like gate size, gate location, steering angle for color box and sv angle for velocity measurement.

Is it possible to modify the above mentioned settings using the application we develop using CAST API or mobile api?

Thanks

**Comment by clariusk** [comment]
The API does provide some parameter control, but not around the parameters you mention, you can view the user functions supported here:
https://github.com/clariusdev/cast/blob/master/src/include/cast/cast_def.h
