### ISSUE TITLE
"Pre-shadow" artifacts in basic capture

### ISSUE THREAD

**Issue by eclarius** [clariusdev/cast#59]
Hello,

We are making a very simple capture of water in a box and passing the finger in front of the probe.

*without finger*
<img src="https://user-images.githubusercontent.com/102674190/164723933-99d19d0f-4ff6-4e56-98e3-8038ab4af412.jpeg" alt="drawing" width="300"/>

*with finger*
<img src="https://user-images.githubusercontent.com/102674190/164723922-2290e771-66da-4680-bb59-f6eada976da0.jpeg" alt="drawing" width="300"/>

How do you explain the apparition of a "pre-shadow" (red arrow) when the finger (green box) enters the probe view? Is there some per line log compression or gain applied in the abdomen presets in B-mode? We have disabled autogain. We had never seen such artifacts (we coined the "pre-shadow" name) and we don't understand how more distant objects can modify the closer part of the image. This artifact is not present in images taken with the Butterfly probe.

Thank you for your help.

**Comment by clariusk** [comment]
that is strange indeed! im not sure, but it must be some reflection phenomenon, perhaps amplified because Clarius uses multi-beamforming technology.

**Comment by eclarius** [comment]
We saw in this [issue](https://github.com/clariusdev/raw/issues/5) that multi beamforming should be disabled in RF mode. This is a capture of the RF buffers (through cast API) + envelop detection + resizing (to have the correct aspect ratio). You can see the finger moving and the pre-shadow following it. 

https://user-images.githubusercontent.com/102674190/165090900-2686b078-da2b-4663-a6ab-5fbac94208fc.mov

We discarded the hypothesis of a reflection as the finger casts shadows on the top of the image (i.e. the past of the beam so by causality future should not influence the past). However it could be an artifact of:
- Reconstruction
- Demodulation
- (multi-)beamforming
- Time gain
- Log compression

We went to the "rawest" signal that you provide and there is still something wrong. What do you suggest to investigate this bug ? Can you reproduce it with C3 probe + water box + finger.

Thanks a lot.

**Comment by clariusk** [comment]
thanks, I spoke to our in-house scientist. they said it makes sense and that what is happening is that your finger is actually blocking the reflections bouncing from the bottom of the tank,essentially creating a higher SNR in that area compared to the areas not blocked by your finger - where the reflections are bouncing continuously. So in fact you are not seeing a shadow but rather the signal without the reflections interfering. You can actually see this if you just look at the bubbles in the image, in front of the finger they still exist, so are not actually behind a 'shadow'. Interesting phenomenon, I would say the way to get around that is to use a deeper tank where the reflections are minimized (ie. our acoustic tanks we use here are 36" deep), or you can line the bottom of the tank with absorbing material (ie. from: https://www.acoustics.co.uk/product_category/high-frequency-anechoic-absorbers/)

**Comment by eclarius** [comment]
Hello. Thanks a lot for your insightful answer. Could you give us some reference explaining how the SNR affect the ultrasound image? We are not sure to understand if this computation is done per beam or not.

**Comment by clariusk** [comment]
SNR would be calculated by yourself, but essentially having reflections bounce back is creating artificial noise, so the way to increase SNR is to remove reflections
