### ISSUE TITLE
Possible problem with micronsPerPixel value in ClariusProcessedImageInfo

### ISSUE THREAD

**Issue by jnunomcosta** [clariusdev/cast#60]
Hey there

I was trying to validate how correct the given pixel spacing value of the Ultrasound Image was, to do that I multiplied the image height by the micronsPerPixel value and measured the difference between that result and the current depth. 

The Height was calculated by eliminating the pixel rows with every pixel equalling 0.

The problem I'm facing is that the result of the Height value times micronsPerPixel constantly gives me a value like 0.2cm short of the desired result (1cm depth results in a 128 pixel height and the result of its calculation was the closest to the desired 1cm).

I'm I missing some variable?

Thanks in advance.

**Comment by jnunomcosta** [comment]
> just to confirm, the desired depth of 1cm was retrieved from the Clarius App?

Yes, the depth was 1cm in the app, and when I use the in app distance widget, the height was also 1cm.

**Comment by clariusk** [comment]
to verify then, I would:
- run App @ 1cm
- increase gain max or scan something
- obtain cast image - set output size 800x800
- save image in App
- end exam in App and local export (I believe default is 800x800)
- compare images, should essentially match 1:1

**Comment by jnunomcosta** [comment]
> to verify then, I would:
> 
> * run App @ 1cm
> * increase gain max or scan something
> * obtain cast image - set output size 800x800
> * save image in App
> * end exam in App and local export (I believe default is 800x800)
> * compare images, should essentially match 1:1

Thanks for the help, I doubled checked the values my app gives me and they are consistent with the ones on the Clarius App, now another question arose, what does changing the Width and Height values in the cusCastInit mean in practice? Does the micronsPerPixel value stay correct and does it still have a 1:1 aspect ratio axially/laterally?

Thanks in advance

**Comment by clariusk** [comment]
when you change the output dimensions, the microns per pixel will adjust accordingly - and it is always 1:1 ratio. You would change this to modify the scan conversion routine to output to a smaller or larger surface. The drawback of outputting to a larger surface is you will feel the image is lower resolution due to pixel stretching, so typically 640x480 or 800x600 are nice standard resolutions to use

**Comment by jnunomcosta** [comment]
Makes sense, thank you

**Comment by jnunomcosta** [comment]
Hey again, what exactly is the Width and Height of the Rendered Image parameter of the cusCastInit function? If the width and height is 3840x2160 (4K) is the Ultrasound image upscaled?

**Comment by clariusk** [comment]
yes, the image is upscaled, but not with a truly higher resolution, so the image will get more pixelated
