### ISSUE TITLE
IP address and port not shown in iOS app; device restarted

### ISSUE THREAD

**Issue by yuanagain** [clariusdev/cast#63]
Hi, I was wondering what my next steps should be if I don't see the device IP address and port (for Cast) are not displayed.

I've tried:

1) Setting cast audience to both "everyone" and "institution"
2) Trying both the device's Wifi network and the office's LAN
3) Restarting the device using both the probe's buttons and the app's interface

Please advise; thank you!

**Comment by julien-l** [comment]
Hi, ensure you have a research license. Contact your sales representative for more information.

**Comment by yuanagain** [comment]
Got it, thank you
