### ISSUE TITLE
Zoom/Dezzom

### ISSUE THREAD

**Issue by eclarius** [clariusdev/cast#64]
Hello,

We are testing the C3 probe on an agar block (10x10x30cm) and we obtain weird artifacts when zooming/dezooming. Can you tell us what happens when we zoom in the app? Does the frequency change? Is it only a postprocessing of the image? We see the same artifacts in the raw/RF images captured with the Cast API.

https://user-images.githubusercontent.com/102674190/166469151-2d372f98-52d8-41ce-882b-79f71f99d113.mp4

<img width=200 src="https://user-images.githubusercontent.com/102674190/166469848-8d0fe340-a1a1-4f9e-b781-10ce282672ba.png"/>

Thank you for your help!

**Comment by clariusk** [comment]
again, phantoms, especially when the beams hit the bottom surface produce large reflections, so you are seeing the effect of these reflections that look slightly different based on the depth - which changes the delay time between beams

for more consistency, try turning off auto-gain as well
