### ISSUE TITLE
Caster Qt sample doesn't receive any image with v9.0.0

### ISSUE THREAD

**Issue by daudrain** [clariusdev/cast#65]
**System information (version)**

- Ubuntu 20.04
- Qt 5.15
- Clarius App APK: [v9.0.0 provided on github](https://github.com/clariusdev/mobileapi/releases/download/v9.0.0/clarius-v900-apk.zip)
- Clarius Cast Lib: [v9.0.0 provided on github](https://github.com/clariusdev/cast/releases/download/v9.0.0/clarius-cast-v900-linux.zip)

**Result**
Caster application connects to the probe.
`Caster::event` doesn't receive any `IMAGE_EVENT`.
FREEZE and BUTTON are correctly received. 

The following screenshot shows the logs after adding few `qDebug`:
![caster](https://user-images.githubusercontent.com/3604504/166743128-8174c88d-2a54-48e7-9e3e-5c857aafdd25.png)

**Question**

Is this issue specific to the github 9.0.0 apk?
Is it required to upgrade to 9.1.0?

I am asking because we're using an another application integrating Clarius Cast 9.0.0 and it also doesn't receive any image.

Thank you,
David

**Comment by clariusk** [comment]
yes, the protocols change between versions so the API binaries must be kept in sync with the App install

**Comment by daudrain** [comment]
The observed behavior looks to be linked to the computer I am using.
`caster` command line example works like a charm on another computer, it logs it receives new image which is not the case on my computer.
However the network bandwidth is high when the probe is not frozen, and almost zero when it is frozen. Looks like data are streamed over the air but libcast doesn't get them.

**Comment by clariusk** [comment]
looks like this would be a firewall issue then, so make sure ports are unblocked

**Comment by daudrain** [comment]
@clariusk Good catch, this was the issue. Thx
