### ISSUE TITLE
sigsev from libcast when terminating application 

### ISSUE THREAD

**Issue by daudrain** [clariusdev/cast#67]
**System information** 

- Ubuntu 20.04
- Qt 5.15
- Clarius App APK: [v9.1.0 provided on github](https://github.com/clariusdev/mobileapi/releases/download/v9.1.0/clarius-v910-apk.zip)
- Clarius Cast Lib: [v9.1.0 provided on github](https://github.com/clariusdev/cast/releases/download/v9.1.0/clarius-cast-v910-linux.zip)

**Result**

A SIGSEGV occurs when `caster` example terminates.
```
Thread 1 "caster" received signal SIGSEGV, Segmentation fault.
0x00007ffff126a7e2 in ?? () from ../../../lib/libcast.so
```

After narrowing down, it looks like invoking `cusCastInit` leads to SIGSEV when application terminates.

The same behavior occurs with 8.6.0 or 9.0.0, and this prevents an internal app to cleanly terminates.

**Comment by clariusk** [comment]
thanks, something in how Qt event loop is shutting down I believe. For now marked as known issue with no fix planned.
