### ISSUE TITLE
Unable to run pycaster.py (version `GLIBCXX_3.4.29' not found)

### ISSUE THREAD

**Issue by nalindas9** [clariusdev/cast#71]
I am unable to run pycaster.py. Getting this error - 
![issue](https://user-images.githubusercontent.com/44141068/169254969-96aa1a92-a4dc-4fd5-afab-1d4021bfda7f.png)

 I followed the steps listed in this [README](https://github.com/clariusdev/cast/blob/master/src/python/README.md).

Current system:
- Ubuntu 18.04
- Python 3.7.5 (running in a virtual environment)

Would appreciate if I could get help on this to understand why this is happening and the solution.

Thanks,
Nalin

**Comment by nalindas9** [comment]
**UPDATE**

Able to get past that error by using the latest release. Getting a new error now - 
![issue2](https://user-images.githubusercontent.com/44141068/169278957-73e3d2df-ef64-4f66-a0b2-46ec4e412139.png)

Can you let me know why this is the case?

**Comment by julien-l** [comment]
Try to run with python 3.8, see discussion here https://github.com/clariusdev/cast/issues/45.

**Comment by nalindas9** [comment]
Tried running with python 3.8.10 as discussed in [#45](https://github.com/clariusdev/cast/issues/45). But getting the same error. Using Ubuntu 20.04.2 LTS. 
Current libs folder includes -
```
libcast.so  pycaster.py  pyclariuscast.so  pysidecaster.py  README.md
```
![issue](https://user-images.githubusercontent.com/44141068/169449296-a349e77a-b4ae-4e98-898e-9d5b73ce6361.png)

The output of 
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX 
```
gives me this - 
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Do I need to update my GCC compiler? Else what is the alternate solution?
Thanks

**Comment by nalindas9** [comment]
Okay, I was able to update the `libstdc++` and now the output of 
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX 
```
shows this 
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Now I am getting this error - 
![issss](https://user-images.githubusercontent.com/44141068/169637615-59eefe60-84bb-4678-963e-bb070434ad13.png)

Any idea or solution for this?

**Comment by clariusk** [comment]
note we now deploy pyclariuscast libraries for different python versions, this should make it simpler to use this tool, also ubuntu 20.04 and 22.04 libraries have been deployed to make target version specific dependencies without users having to backport
