### ISSUE TITLE
Wi-Fi link speed

### ISSUE THREAD

**Issue by daudrain** [clariusdev/cast#73]
Hi Clarius Support,

Last week, I noticed the link speed between my Ubuntu laptop and Clarius linear probe l15hd was about 6Mb/s, and sometimes I observed lags in image streaming on Android Tablet and Ubuntu laptop.

I tested today in another room (25 meters away from last week) and link speed was about 36 or 54Mb/s.

Here are few questions to troubleshoot/reduce the lags:

- May the other wifi networks lead the probe to select a low speed link?
- `Wi-Fi Search` has been enabled, should `connectivity resolution` lead to better result?
- Does Clarius Android App request a bigger image from linear probe when it is in portrait mode than landscape mode ?

Thank you,
David

**Comment by clariusk** [comment]
- Yes, Wi-Fi links can be affected by outside interference from other networks overlapping the Wi-Fi channel, typically using the probe's Wi-Fi is better than a WLAN due to knowing that the ultrasound data is the only traffic
- Wi-Fi search is useful in busy areas where channel selection can try and be optimized
- Orientation of image will not affect streaming size

**Comment by daudrain** [comment]
I did new tests in the room where lags occur the most and it also happens when link speed using Probe's Wi-Fi is supposed to be 54Mb/s.
I also tested using `caster_qt` example which requests a new image output size (cusCastSetOutputSize) when the application window is resized  and the network bandwidth looks to be stable what ever the window size: between 1Mb/s and 1.2Mb/s with the linear probe

Is the streaming size independent from the requested output size?

I am looking for a solution to reduce the streaming bandwidth to reduce lags.

**Comment by clariusk** [comment]
- yes, the streaming size is independent from the output size
- you could try using [eco mode](https://support.clarius.com/hc/en-us/articles/360020579452-Conserving-Power), which will reduce the frame rate somewhat and thus reduce bandwidth

**Comment by daudrain** [comment]
I looked more into Wi-Fi environment: it looks like the lag issue occurs the most when the channel 165 is used.

Eco mode does reduce streaming bandwidth about 25% for Linear probe, we will do more to see if lags occur less.

**Comment by daudrain** [comment]
We did not find any appropriate setup to workaround interference so we moved to an another room where image streaming is much more stable.
Thanks for the support

**Comment by daudrain** [comment]
Dear Clarius Support,

Even after moving to another room, we're still facing lags. Even ecomode may lag also.

Looking at the incoming network traffic on our laptop, the UDP stream packets received from the probe have a size of 1514 bytes which is greater than laptop Wi-Fi adapter MTU and also Samsung Galaxy Android tablet Wi-Fi adapter MTU.

Does the probe Wi-Fi adapter use a MTU larger than 1500?

**Comment by daudrain** [comment]
No issues when the tablet is the only device connected to the probe.
Lags occur when the laptop is connected via libcast: lags appear first on the laptop, and may also occur on the tablet in worst cases. It looks like Clarius App on the tablet is luckier than ubuntu apps integrating libcast.

Note that when lags become visible on Clarius App, the displayed Frame Rate doesn't change.

**Comment by daudrain** [comment]
We tested last year using a separate router , and it was very much more laggy. We fell back on using probe Wi-Fi which was more conclusive.

**Comment by daudrain** [comment]
Yesterday evening, I went to an area with zero Wi-Fi and I could not get any lag using Linear probe @ 7cm depth: bandwidth was most of the time about 1.2mb/s, sometimes 1mb/s.
In term of received frame rate, most of the time it was 15 fps, sometimes 16 , very few times 12 for a very short time.
Overall it was very stable in that area (in a park) even when the probe was hot.

**Comment by clariusk** [comment]
Well that's dedication to testing in a park, so yes channel interference definitely can have an impact. I'm playing around with 40mhz channel bandwidths, that may offer some improvements in the future
