### ISSUE TITLE
Symbol not found (9.3.0)

### ISSUE THREAD

**Issue by yuanagain** [clariusdev/cast#74]
When attempting to run either Python example, we get:
```
(master) ✗ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. python3 pycaster.py
Traceback (most recent call last):
  File "pycaster.py", line 5, in <module>
    import pyclariuscast
ImportError: dlopen(/Users/yuan/dandelion/cast/clarius-cast-v930-macos/pyclariuscast.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: ./libcast.dylib (which was built for Mac OS X 12.3)
  Expected in: /usr/lib/libc++.1.dylib
```

Please advise! Dependencies appear to be installed and located as desired. Contents of the dir are thus:
```
ls
README.md        libcast.dylib    pycaster.py      pyclariuscast.so pysidecaster.py
```

**Comment by yuanagain** [comment]
> It seems you don't have the C++ lib install, make sure you have `clang` installed. It also probably comes with Xcode.

Hi Julien, thank you for the quick reply. Clang is in fact installed:

```
clang --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Should `libcast.so` be in the 9.3.0 release, or has it been replaced by `libcast.dylib` and the README is just out of date?

**Comment by yuanagain** [comment]
> Our builder uses clang 13.0.0. Try updating your clang. My system has clang 13.1.6 and runs the python example correctly.
> 
> File `libcast.so` is the shared lib for Linux, on Mac OS the extension is `dylib`.

Updating `clang to 13.0.0` moves it along, but now I'm getting:

```
Traceback (most recent call last):
  File "pysidecaster.py", line 5, in <module>
    import pyclariuscast
ImportError: dlopen(/Users/<>/clarius-cast-v930-macos/pyclariuscast.so, 0x0002): Library not loaded: @rpath/libcast.dylib
  Referenced from: /Users/<>/cast/clarius-cast-v930-macos/pyclariuscast.so
  Reason: tried: '/usr/local/lib/libcast.dylib' (no such file), '/usr/lib/libcast.dylib' (no such file)
```
after running:
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. python pysidecaster.py
```

I'm guessing the `LD_LIBRARY_PATH` env variable needs to be set slightly differently?

**Comment by clariusk** [comment]
might be DYLD_LIBRARY_PATH on macOS

**Comment by yuanagain** [comment]
> might be DYLD_LIBRARY_PATH on macOS

That's it, thank you

Closing; now back at #61: https://github.com/clariusdev/cast/issues/61
