### ISSUE TITLE
Updated to Clarius App 9.3 and python code no longer works

### ISSUE THREAD

**Issue by geisjb01** [clariusdev/cast#75]
In order to attempt to fix an issue with connecting to our probe over local WIFI (still being resolved) we updated our Clarius app to version 9.3 at the recommendation of the support staff. However, now we're left with another issue which is that when running the python code with fresh binaries for version 9.3 the connection is able to be initialized but then immediately fails every time. This is while being directly connected to the probe's WIFI and the firewall is disabled.

**Comment by geisjb01** [comment]
Of course. We appreciate the help.
![image](https://user-images.githubusercontent.com/106112354/171457047-993865c1-7ed3-4735-a108-6a41a3df711c.png)

**Comment by clariusk** [comment]
unfortunately the python library doesn't provide error codes like the C program does, if you can compile the 9.3 C program you'll get a specific message of the failure

**Comment by clariusk** [comment]
if you're using windows, with an msvc compiler and visual studio code, you should be able to create a simple project using the console application - note there's some boost used to parse command line args, suggest removing and hardcoding to limit that dependency

**Comment by mcfly3001** [comment]
I got the same error thoug found out that calling `cast.isConnected()` returns `True`. Also I am able to receive the image data. I have the problem though, that after connecting all other calls of the API (except for `cast.isConnected()` throw the Exception:

```
RuntimeError: future already retrieved
```

This error came up after updating to version 9.3.

**Comment by mattiaspaul** [comment]
we have the same error. In addition the WiFi connection of the App now frequently fails regardless of whether we use the API or not. So we cannot reliable establish an image stream at all. Did someone from Clarius check whether the C++ code still works before auto-updating the software version?

**Comment by clariusk** [comment]
> I got the same error thoug found out that calling `cast.isConnected()` returns `True`. Also I am able to receive the image data. I have the problem though, that after connecting all other calls of the API (except for `cast.isConnected()` throw the Exception:
> 
> ```
> RuntimeError: future already retrieved
> ```
> 
> This error came up after updating to version 9.3.

@mcfly3001 I have devoted some time to updating the pyclariuscast (was a side project, and now I see it's valuable to this community), I have fixed many issues and you'll be able to test in 9.4 release, thanks for your patience

**Comment by mcfly3001** [comment]
Thanks for the update. I also send the logs to your team. Is there a rough estimate when the new release will be published? Thanks!

**Comment by clariusk** [comment]
we typically hit our pilots mid-month, we can pre-release some new binaries at the same time, thanks!

**Comment by mattiaspaul** [comment]
superb, thanks for the update. We were able to get the C++ code working for our application as a work around, but would also highly appreciate the update on pyclariuscast! @clariusk if you release new binaries could you please also consider compiling the Mac library as universal (arm64 + x86_64)? While it is possible to run the code in Rosetta-emulation it's quite a big performance hit on Apple M1.

**Comment by geisjb01** [comment]
After updating to 9.4.0 and testing the python code works. So far it  is working much better and the connection is much more stable than it was on the previous versions I worked with. Thanks!!!

**Comment by clariusk** [comment]
great to hear, thanks!
