### ISSUE TITLE
Previous Clarius Versions

### ISSUE THREAD

**Issue by ChristophG123T** [clariusdev/cast#76]
Hi, I was wondering if we could access and use past Clarius versions for our research. Whenever a new update is released, it automatically updates the app and Clarius, which means Plus library and 3D Slicer may need to be updated to work. This is a massive pain since a project can work one day and then stop the next, with us having to download Plus and Slicer again once they've also been updated to continue working.
Thanks, 
Chris

**Comment by clariusk** [comment]
yes, you can find Android APKs [here](https://github.com/clariusdev/mobileapi/releases), going back to version 7. note we typically release a new App to the stores every 3 - 4 months on average.
