### ISSUE TITLE
Compiling the executable file from the source code

### ISSUE THREAD

**Issue by MirkoJ1991** [clariusdev/cast#77]
Hello, 
Being relatevely new to your product, I spoke to an engineer of the technical team which informed me about this API to adapt the CLARIUS acquisition for research purposes. My institution has a Microsoft Visual Studio IDE subscription and I was thinking I could use it to build the executable from the source code. However I read in previous issues that the project is compilable through QT creator which as far as I understood is a licensed IDE that require an additional subscription with the possibility to use an open source suite.
Is the latter enough to build the solution or do I need the full QT IDE ?

**Comment by MirkoJ1991** [comment]
UPDATE: I manged to download and install QT creator however when i load the project and build it there are some missing files. 
Specifically the error I get from the compiler is:

LINK : fatal error LNK1104: impossibile aprire il file 'cast.lib'
jom: C:\Users\REHE-Lab2\Downloads\cast-master\src\example\build-caster-Desktop_x86_windows_msvc2019_pe_64bit-Debug\Makefile.Debug [debug\caster_qt.exe] Error 1104

**Comment by clariusk** [comment]
note you cannot use the MinGW compiler, we only distribute binaries built with MSVC
