### ISSUE TITLE
Casting port 0 on 9.4.0

### ISSUE THREAD

**Issue by yuanagain** [clariusdev/cast#78]
Hi, I was wondering what it means for the casting port to be set to 0:

![IMG_945EB7507BA3-1](https://user-images.githubusercontent.com/6503523/176050764-858986ae-f51c-4eaa-802f-c52f2578149d.jpeg)

The SDK doesn't accept "0" as a valid argument for port:

```
DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:. python pycaster.py --port 0 --address 192.168.0.182
one or more arguments are invalid
usage: pycaster.py [-h] --address IP --port PORT [--width WIDTH] [--height HEIGHT]
```

**Comment by julien-l** [comment]
The port should not be zero, it seems to be a bug. Try to reconnect to the probe to fix. If it does not work, try to restart the probe.

**Comment by julien-l** [comment]
Also verify that casting is not disabled in app: Menu > Settings > Cast > select Research.

**Comment by yuanagain** [comment]
Thanks @julien-l; indeed, I forgot to check that our cast settings were preserved when we updated to 9.4.0 on Testflight. Thank you

**Comment by clariusk** [comment]
when setting the Cast port to "Research" it may get reset if you connect to another probe not licensed or demo probe. if you're connecting to the same probe all the time, should not be a problem. Note starting in 9.3, settings are also synchronized with our cloud, so you should not have to reset after re-installing the App.
