### ISSUE TITLE
New export header doesn't support visual studio

### ISSUE THREAD

**Issue by smistad** [clariusdev/cast#8]
Your new export header cast_export.h (https://github.com/clariusdev/cast/blob/master/src/include/cast/cast_export.h) doesn't support visual studio (MSVC). 
MSVC doesn't recognize __attribute__((visibility("default"))), but instead use __declspec(dllimport/export).

See your previous export header which worked fine: https://github.com/clariusdev/cast/blob/c932558cdb0283e9d4d9e3c7ecfdba433867ff09/src/include/listen/listen_export.h

**Comment by clariusk** [comment]
thanks, should be fixed
