### ISSUE TITLE
Performance for streaming video?

### ISSUE THREAD

**Issue by yuanagain** [clariusdev/cast#80]
Hi, I was wondering what performance one can expect for using the Cast API to stream video--I notice the Python examples are just capturing stills. Thanks!

**Comment by clariusk** [comment]
when streaming through the Cast API, images should come at the native ultrasound frame rate (the App has an option to display this on the screen). Since there are 2 streams - 1 to the App and 1 via the API, the bandwidth is increased so it's best to ensure you're on the probe's access point.
