### ISSUE TITLE
Caster Example Program: qopenglfunctions created with non-current context

### ISSUE THREAD

**Issue by dgblack** [clariusdev/cast#82]
Hi,

I am trying to get the caster example program working in C++.  It builds and runs and actually connects to the device over WiFi. However, very shortly after connecting (<1sec usually), it gives the following error message and closes the console window.

`qopenglfunctions created with non-current context`

I know the connection is successful because I have it freeze the imaging as soon as it connects, just before it crashes, and the imaging on the phone app does indeed freeze. I am not very familiar with Qt and OpenGL, but the error seems related to them. I thought the command-line example program would not depend on them, though?

I am using the following:
- Windows 10
- Visual Studio 2022
- Platform target: x64
- Clarius App v9.3.1
- Release 9.3.0 binaries
- Clarius C3HD

Side note, the main readme says a Visual Studio solution is provided to help with compilation, but I couldn't find one. Not that it's very difficult to create one...

Thanks in advance for your help!
David

**Comment by julien-l** [comment]
Hello the cast library uses OpenGL and Qt to do the scan conversion from raw images to B-Images, we are re-working the OpenGL code these days and this should prevent the crash you noticed. The update should come in the next few months thanks.

**Comment by dgblack** [comment]
Makes sense, thanks! Do you know if there is a relatively simple workaround I can use in the meantime?

**Comment by clariusk** [comment]
there hasn't been any issues typically running the latest SDK thusfar, I would check your Qt install to ensure platform plugins are available. you'll notice this up front if you try to build the Qt demo program.

**Comment by dgblack** [comment]
I could get the Qt demo working from Qt Creator, but not when I tried to run the executable on its own. I fixed this by adding the following environment variable.
`QTDIR = C:\Qt5\5.15.2\msvc2019_64` 
This also then solved the problem I was having with the caster demo program. Stupid mistake :) Works great now so I'll close the issue. Thanks for your help!
