### ISSUE TITLE
Help with processing image

### ISSUE THREAD

**Issue by yuanagain** [clariusdev/cast#83]
Hi, I've gotten some Python examples running and am trying to inspect the images being returned by the API. I'd ultimately like to stream the video feed via webRTC to a dashboard. With the following code I get a strange looking image; I suspect I'm just not parsing the data properly. Any help would be appreciated!

Example image:
![processed_image](https://user-images.githubusercontent.com/6503523/183772718-b90cb447-9ce8-4705-a243-375c84ad0c72.png)

Code:
```py
def newProcessedImage(image, width, height, bpp, micronsPerPixel, timestamp, imu):
   ...
    if bpp == 32:
        img = Image.frombytes("RGBA", (width, height), image)
    else:
        img = Image.frombytes("L", (width, height), image)
    img.save("processed_image.png")
    return
```

**Comment by clariusk** [comment]
thanks for checking in on this, a few things I noticed:
- in 9.3 we changed the definition of "bpp" to "size of image", so to calculated bpp you must now calculate: bpp = (sz / (width * height)) * 8 -- I'll update the code to reflect that change
- I tried saving jpg and the save function crashes, but png seemed to be alright - i did not dig into why PIL does so

**Comment by yuanagain** [comment]
> thanks for checking in on this, a few things I noticed:
> 
> * in 9.3 we changed the definition of "bpp" to "size of image", so to calculated bpp you must now calculate: bpp = (sz / (width * height)) * 8 -- I'll update the code to reflect that change
> * I tried saving jpg and the save function crashes, but png seemed to be alright - i did not dig into why PIL does so

Gotcha, thank you @clariusk; I'll watch for the update to dimension calcs. 

As for saving to jpg vs png--also not sure. I was able to save to jpg I believe, actually.
