### ISSUE TITLE
DLL load failed while importing pyclariuscast

### ISSUE THREAD

**Issue by AREs22git** [clariusdev/cast#84]
Previously was using Cast for Clarius App 9.4.0 on Windows 11 system. In order to add the system to the local domain the system needed to be wiped and moved to Windows 10. After adding the device to the domain we wanted to reinstall the cast software. Installed python v 3.8.10 using windows installer, updated pip to 22.2.2, updated Pillow to 9.2.0, installed PySide2 version 5.15.2.1. We then made sure the code and corresponding cast libraries were in the same directory. (These are the same steps as what we did to have the code run when it was on Windows 11) After attempting to run both python examples we encountered the same error where importing the pyclariuscast library fails.

"ImportError: DLL load failed while importing pyclariuscast: The specified module could not be found."

Tried uninstalling and reinstalling and encountered the same issue.

**Comment by clariusk** [comment]
looks like you already confirmed that you're on python 3.8, maybe double check, as this thread also pinpointed the same error message to the version: https://github.com/clariusdev/cast/issues/46

**Comment by AREs22git** [comment]
After a quick double check I can confirm the system is running python 3.8.10. I'm quite perplexed because I followed the exact same procedure as I had when setting it up previously (Thoroughly documented my process the first time through with no issues)

**Comment by clariusk** [comment]
ok, thanks for checking, it's unlikely the python dependencies (pillow, etc) have any impact on finding the DLL, so perhaps check your path, and add an explicit environment variable to where to find the location of the DLL

**Comment by AREs22git** [comment]
Tried adding a system environment variable to the location of the DLL and produced the same error after a system restart to ensure the changes went into effect. 

Also, separately, tried placing the DLL in the LIB\site-packages folder and ensured it appears in the Python PATH which continued to produce the same result.

**Comment by clariusk** [comment]
you would want to make an exception for python.exe, which probably isn't the safest, but it's the only method sso far that has worked for users based on similar messages I've seen on the forum
