### ISSUE TITLE
Console app never closes in v9.3.0: "QEventDispatcherWin32::wakeUp: Failed to post a message (Invalid window handle.)"

### ISSUE THREAD

**Issue by danilogr** [clariusdev/cast#86]
In the current version (9.3.0), the console sample app never closes. Despite returning from `main`, the app never closes. This seems to be related to how the library is managing the Win32 application. For example, if we modify the sample to look like this:

```c++
/// main entry point
/// @param[in] argc # of program arguments
/// @param[in] argv list of arguments
int main(int argc, char* argv[])
{
    int rcode = init(argc, argv);
    return rcode;
} /// <----------------------------- Somehow it doesn't close past this 
```

This is what the console shows:
```
starting caster...WARNING: QApplication was not created in the main() thread.
QEventDispatcherWin32::wakeUp: Failed to post a message (Invalid window handle.)
```
I am compiling this on Windows x64 using Visual Studio. Visual Studio can't show me the correct stack trace because it is running on External Code. 

Any hints on what we can do here? Is it because I am not compiling it through QT?

**Comment by danilogr** [comment]
Calling `custCastInit` is enough to enter into this state:

```c++
    // initialize with callbacks
    if (cusCastInit(argc, argv, keydir.c_str(), newProcessedImageFn, newRawImageFn, newSpectralImageFn, freezeFn, buttonFn, progressFn, errorFn, width, height) < 0)
    {
        ERROR << "could not initialize caster" << std::endl;
        return FAILURE;
    }

    if (cusCastDestroy() < 0)
    {
        ERROR << "cusCastDestroy failed" << std::endl;
        return FAILURE;
    }

```

**Comment by julien-l** [comment]
Hello, the examples start an infinite loop accepting user commands. It will only end when typing `q`.

**Comment by danilogr** [comment]
I know. If you take a look at the modified example [here](https://github.com/clariusdev/cast/issues/86#issue-1378273720), I removed the console thread for the sake of testing. When I bring it back, pressing `q` ends the infinite loop but the app never quits.

I am not sure what is happening because, well, the application returns from main. I imagine it has to do with how QT (on the library side) is interacting with Windows SDK. I wonder if you have any insights from your side.

**Comment by danilogr** [comment]
I reproduced the same issue on on QT.  Using VS2019 x64 as the compiler, QT 5.15.2:

![EnvironmentVariablesGITFLS](https://user-images.githubusercontent.com/1302815/191108798-2baa8464-23a5-4391-8da9-949454e43a62.PNG)

**Comment by danilogr** [comment]
I reproduced the same issue on on QT. Using VS2019 x64 as the compiler, QT 5.15.2:

![CastAPI](https://user-images.githubusercontent.com/1302815/191111168-f2397204-f7e7-4817-961e-2f723ef8ca2e.gif)

**Comment by clariusk** [comment]
similar to https://github.com/clariusdev/cast/issues/67, no plans to try and remedy currently, as we have to use Qt in strange ways to get the Cast API working.

**Comment by danilogr** [comment]
Is that an issue with the OEM API too ?

**Comment by clariusk** [comment]
yes, both APIs have a large amount of Qt behind them
