### ISSUE TITLE
Initializing, destroying, and then initializing the API again freezes the application

### ISSUE THREAD

**Issue by danilogr** [clariusdev/cast#87]
There seems to be a weird bug with `cusCastInit`. The method never returns when called for a second time (after `custCastDestroy` is called). The easiest way to reproduce this bug is by tweaking the console sample to do the following:

```c++
cusCastInit(argc, argv, keydir.c_str(), newProcessedImageFn, newRawImageFn, newSpectralImageFn, freezeFn, buttonFn, progressFn, errorFn, width, height);

cusCastDestroy();

cusCastInit(argc, argv, keydir.c_str(), newProcessedImageFn, newRawImageFn, newSpectralImageFn, freezeFn, buttonFn, progressFn, errorFn, width, height);
```

I am working on an application that dynamically loads external SDKs such as the CAST api and unloads them whenever it is done using it. In this workflow, sometimes a library is loaded again when it needs to be used for a second time. Unfortunately, the CAST API gets into a weird state and freezes the application, never returning from a `cusCastInit` call. It would be great if that wasn't the case.

**Comment by julien-l** [comment]
Hi this looks like a bug indeed we will investigate thanks for reporting!

**Comment by clariusk** [comment]
I'm testing our upcoming release, and cannot reproduce (on Linux), so may be fixed.

**Comment by clariusk** [comment]
i hath confirmed in windows the issue does not occur as well - so stay tuned for v10
