### ISSUE TITLE
v10.0 won't compile on Visual Studio (Windows) due to missing dllimport in cast_export

### ISSUE THREAD

**Issue by danilogr** [clariusdev/cast#88]
Visual Studio 2019 (v120, Windows x64) won't compile applications with the new version because of a missing `dllimport` directive. It used to be there in the previous version, but it was now removed. Adding it back fixes the issue.

Fix:
```
#     ifdef _MSC_VER
#       define CAST_EXPORT __declspec(dllimport)
#     else
#       define CAST_EXPORT __attribute__((visibility("default")))
#     endif
```

You can find it here: https://github.com/clariusdev/cast/commit/94e32ea294956c50f5b62a0c3de507057cccb271#r85304808

**Comment by clariusk** [comment]
thanks, I've updated to the previous version
