### ISSUE TITLE
Are there new app store versions for v10.0 ?

### ISSUE THREAD

**Issue by danilogr** [clariusdev/cast#89]
I am using CAST API with the iOS app. I just tried the new library, but I keep getting "Error software revisions are different".
Do I have to wait for a new Android or iOS app version?

**Comment by clariusk** [comment]
the new version 10.0 App is in pilot: https://support.clarius.com/hc/en-us/articles/360019548852-Joining-the-Pilot-Program

**Comment by danilogr** [comment]
Thank you! That worked! It would be great if this were added to the release info or perhaps the readme file!
