### ISSUE TITLE
Cast Examples Not working

### ISSUE THREAD

**Issue by dslunde** [clariusdev/cast#9]
So I've been trying to get the examples up and running as a way of ensuring everything is working, and that is where the problems occur.  The issues I ran into are these:
1) In trying to run the python wrappers, the statement import pycast throws an error.  The full error is
Traceback (most recent call last):

  File "pysidecaster.py", line 7, in <module>

    import pycast

  File "/anaconda3/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import

    return original_import(name, *args, **kwargs)

  File "/anaconda3/lib/python3.6/site-packages/pycast/__init__.py", line 26, in <module>

    import methods

  File "/anaconda3/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import

    return original_import(name, *args, **kwargs)

ModuleNotFoundError: No module named 'methods'

and when I try to fix it,

Darrens-MBP:python darren$ pip install methods

ERROR: Could not find a version that satisfies the requirement methods

ERROR: No matching distribution found for methods

with a similar situation occuring when I try to run pycaster.py. I also tried following the linux instructions, which allowed me to run pycaster.py on my own machine, but throws an error regarding the @rpath when Casey (our colleague who actually has the scanner) tried repeating the process on her own machine.

2) When trying to compile the C++ example in "caster" into an executable, I get this error:

Darrens-MBP:caster darren$ g++ main.cpp -o run.out

main.cpp:56:10: warning: 'auto' type specifier is a C++11 extension

      [-Wc++11-extensions]

    for (auto i = 0; i < npos; i++)

         ^

main.cpp:293:21: error: no matching constructor for initialization of

      'std::thread'

        std::thread eventLoop(processEventLoop, std::ref(quitFlag));

                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Library/Developer/CommandLineTools/usr/include/c++/v1/thread:408:9: note: 

      candidate constructor template not viable: requires single argument '__f',

      but 2 arguments were provided

thread::thread(_Fp __f)

        ^

/Library/Developer/CommandLineTools/usr/include/c++/v1/thread:289:5: note: 

      candidate constructor not viable: requires 1 argument, but 2 were provided

    thread(const thread&);

    ^

/Library/Developer/CommandLineTools/usr/include/c++/v1/thread:296:5: note: 

      candidate constructor not viable: requires 0 arguments, but 2 were

      provided

    thread() _NOEXCEPT : __t_(_LIBCPP_NULL_THREAD) {}

    ^

1 warning and 1 error generated.

Namely, that the constructor for eventLoop doesn't exist, which is odd, since it seems to have no errors from a technical standpoint, and yet won't compile.  It's 100% possible that I'm just overlooking something very simple, but I can't see a way to get everything up and running correctly.
Let me know whatever other information I can provide to help us figure this out.

**Comment by clariusk** [comment]
#1
- Ensure you PySide2 installed https://pypi.org/project/PySide2/
- You may also have another pycast installed via pip (https://pypi.org/project/pycast/), it may be conflicting with the Clarius pycast (which you should not use pip, but rather place the module within your program structure)

#2 
- See https://gcc.gnu.org/projects/cxx-status.html, c++11 is used in the examples, you'll need to ensure that support is enabled

**Comment by dslunde** [comment]
#1 I think you were right about a conflicting version of pycast.  Would you mind explaining what you mean by "place the module within your program structure"?  I'm not understanding which pycast module to place if it's not the one that I had installed via pip.

#2 Adding in a flag to use the c++11 standard resulted in an architecture error I have no idea what to do with:
(base) Darrens-MBP:caster darren$ g++ main.cpp -o out -std=c++11
Undefined symbols for architecture x86_64:
  "_clariusConnect", referenced from:
      init(int&, char**) in main-742a44.o
  "_clariusDestroyCast", referenced from:
      _main in main-742a44.o
  "_clariusGetUdpPort", referenced from:
      init(int&, char**) in main-742a44.o
  "_clariusInitCast", referenced from:
      init(int&, char**) in main-742a44.o
  "_clariusReadRawData", referenced from:
      processEventLoop(std::__1::atomic<bool>&) in main-742a44.o
  "_clariusRequestRawData", referenced from:
      processEventLoop(std::__1::atomic<bool>&) in main-742a44.o
  "_clariusUserFunction", referenced from:
      processEventLoop(std::__1::atomic<bool>&) in main-742a44.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by clariusk** [comment]
#1 
pip uninstall pycast
Clarius pycast is in the release download for your specific platform: https://github.com/clariusdev/cast/releases
then follow the instructions here for executing: https://github.com/clariusdev/cast/tree/master/src/python

#2
See: https://stackoverflow.com/questions/6141147/how-do-i-include-a-path-to-libraries-in-g

**Comment by dslunde** [comment]
# 1
I tried that earlier, and it led to the @rpath error I mentioned before for my colleague, and this time gave me this error:
(base) Darrens-MBP:python darren$ LD_LIBRARY_PATH=. python3 pysidecaster.py
Traceback (most recent call last):
  File "pysidecaster.py", line 7, in <module>
    import pycast
  File "/Users/darren/opt/anaconda3/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: dlopen(/Users/darren/EMAI/cast/src/python/pycast.so, 2): no suitable image found.  Did find:
	/Users/darren/EMAI/cast/src/python/pycast.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/darren/EMAI/cast/src/python/pycast.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

#2 
No matter how I try to arrange that, it circles me back to the errors I've previously mentioned.  Would mind actually explaining the thought process involved in this, as I have been looking at those previous instructions for quite some time and arrived at the same place I started at when I asked for assistance?

**Comment by julien-l** [comment]
Hi, regarding the C++ example (**2**)

We provide a Makefile to automate the building, simply run `make` in the source folder.

But first, you have to obtain the **cast** library, from the repository's _release_ section here: https://github.com/clariusdev/cast/releases. Download the one corresponding to your App version and platform (it should be version 7.3.0 for MacOs in your case).

Then extract the archive and place the library files in the location that is expected by the Makefile, in `cast/src/lib`. Your file tree should look like this:

    cast/src % tree
    .
    ├── example
    │   ├── cast_plugin_example
    ...
    │   ├── caster
    │   │   ├── Makefile
    │   │   └── main.cpp
    │   └── caster_qt
    ...
    ├── include
    ...
    ├── lib
    │   ├── libcast.dylib
    │   ├── libcast_plugin.a
    │   └── pycast.so
    └── python
    ...

Finally, `cd` into the **caster** example and run `make`:

    cast/src/example/caster/example/caster % make
    mkdir -p build/.//
    c++ -I./ -I../../include -std=gnu++14 -c main.cpp -o build/.//main.cpp.o
    c++ ./build/.//main.cpp.o -o build/caster -L../../lib -lcast -lpthread

**Comment by dslunde** [comment]
Thanks, Julien, that compiled.  Unfortunately, this now brings the executable to the same error the Python wrapper was having, for Casey (and now my machine as well) which is the @rpath error:

(base) Darrens-MBP:caster darren$ ./build/caster
dyld: Library not loaded: @rpath/libcast.dylib
  Referenced from: /Users/darren/EMAI/cast/src/example/caster/./build/caster
  Reason: image not found
Abort trap: 6

**Comment by julien-l** [comment]
Ah right it is looking for the library in the `rpath` but the `rpath` is not set. Run this command after running `make`:

    cast/src/example/caster % install_name_tool -add_rpath @executable_path/../../../lib build/caster

Alternatively, add the `rpath` directly when running `ld` by adding the following lines right under the `LDFLAGS` definition:

    ifeq ($(shell uname -s),Darwin)
	    LDFLAGS += -rpath ${CAST_SDK}/lib
    endif

Then clean and rebuild.

**Comment by julien-l** [comment]
Regarding your Python errors (1):

* `rpath`: please confirm that the `rpath` error mentioned by your colleague pertains to the python example. I suspect it occurred when trying to run the c++ `caster` example.

* python error:

      ImportError: dlopen(/Users/darren/EMAI/cast/src/python/pycast.so, 2): no suitable image found. Did find:
      /Users/darren/EMAI/cast/src/python/pycast.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

  I suspect you downloaded the library for another platform. If you are on MacOS, make sure to download the Darwin libraries.

**Comment by dslunde** [comment]
Perfect, thanks a ton Julien.  The C++ example now seems to be working for me.
I had instructed her to do the python examples when the @rpath error first occurred, and I'm pretty sure she did that part correctly.  I'll double check, though.
So when I download the MacOS files, put those in the python folder, whitelisted them with the command you provided earlier, and then ran 'LD_LIBRARY_PATH=. python3 pysidecaster.py' I get an error where it tells me various (if not all) of the functions are defined twice, once in PySide2/Qt/lib, and once in libcast.dylib (full output below).  Removing libcast.dylib brings back the @rpath error for saying that the image could not be found.

(base) Darrens-MBP:python darren$ LD_LIBRARY_PATH=. python3 pysidecaster.py
objc[40999]: Class QMacAutoReleasePoolTracker is implemented in both /Users/darren/opt/anaconda3/lib/python3.8/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110289198) and /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c190). One of the two will be used. Which one is undefined.
objc[40999]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/darren/opt/anaconda3/lib/python3.8/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110289210) and /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c208). One of the two will be used. Which one is undefined.
objc[40999]: Class KeyValueObserver is implemented in both /Users/darren/opt/anaconda3/lib/python3.8/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110289238) and /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c230). One of the two will be used. Which one is undefined.
objc[40999]: Class RunLoopModeTracker is implemented in both /Users/darren/opt/anaconda3/lib/python3.8/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110289288) and /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c280). One of the two will be used. Which one is undefined.
objc[40999]: Class RunLoopModeTracker is implemented in both /Users/darren/opt/anaconda3/lib/python3.8/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x110289288) and /Users/darren/opt/anaconda3/lib/libQt5Core.5.9.7.dylib (0x11c4a9a80). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSWindow is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bc90) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece4e0). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSPanel is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bcb8) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece530). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSViewMouseMoveHelper is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bc40) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece580). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSView is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bbf0) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece5d0). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSWindowDelegate is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bd58) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece620). One of the two will be used. Which one is undefined.
objc[40999]: Class QCocoaApplicationDelegate is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bd80) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece670). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSApplication is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bdd0) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece6c0). One of the two will be used. Which one is undefined.
objc[40999]: Class QCocoaMenuLoader is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bf10) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece760). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSPanelContentsWrapper is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bf60) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece7b0). One of the two will be used. Which one is undefined.
objc[40999]: Class QMacAccessibilityElement is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c050) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece800). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSImageView is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6bfb0) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece850). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSStatusItem is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c000) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece8a0). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSColorPanelDelegate is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c0a0) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece8f0). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSOpenSavePanelDelegate is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c0f0) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece940). One of the two will be used. Which one is undefined.
objc[40999]: Class QNSFontPanelDelegate is implemented in both /Users/darren/EMAI/cast/src/python/libcast.dylib (0x11aa6c140) and /Users/darren/opt/anaconda3/plugins/platforms/libqcocoa.dylib (0x110ece990). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fbf9481e460) is not the object's thread (0x7fbf90a7c5c0).
Cannot move to target thread (0x7fbf9481e460)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.

Abort trap: 6

**Comment by julien-l** [comment]
If you have an **@rpath** error like so when running the python example:

    cast/src/python % LD_LIBRARY_PATH=../lib /usr/bin/python3 pycaster.py
    Traceback (most recent call last):
      File "pycaster.py", line 5, in <module>
        import pycast
    ImportError: dlopen(/Users/julien/work/src/cast/src/python/pycast.so, 2): Library not loaded: @rpath/libcast.dylib
      Referenced from: /Users/julien/work/src/cast/src/python/pycast.so
      Reason: image not found

Once again you can use `install_name_tool`:

    cast/src/python % install_name_tool -change @rpath/libcast.dylib libcast.dylib pycast.so

Note: I got this error when using MacOS's own python. I did not get the `@rpath` error when using Homebrew's python3.8. However Homebrew's python3.9 caused a crash 🤷‍♂️

**Comment by dslunde** [comment]
Alright, so I hope that fixed the problems with importing pycast, but by changing the @rpath it no longer knows what to do with the imports from PySide2, so I'm not sure.
I also noticed that the command you typed was different from the one in the README, in that you have LD_LIBRARY_PATH=../lib /usr/bin/python3 {clarius_python_example}.py and the README has LD_LIBRARY_PATH=. python3 {clarius_python_example}.py.  When I run the one you typed, I get the error of not knowing PySide2 exists, while running the one in the README gets me the multiple binaries problem.

**Comment by julien-l** [comment]
I found I didn't need PySide2 on MacOS, try removing it: `pip uninstall PySide2`.

I used `LD_LIBRARY_PATH=../lib` because this is where I had previously downloaded the **cast** libraries (from when I tried the C++ **caster** example). Our python README instructs you to download the libraries in the current folder, hence the `LD_LIBRARY_PATH=.` Both `LD_LIBRARY_PATH` and **@rpath** serve the same purpose: specify where the dependent libraries are located.

You probably get different behaviours because you have different library versions in folders `cast/src/python` and `cast/src/lib`.

**Comment by dslunde** [comment]
Alright, I think the reason you didn't need it was because you were just running pycaster.py while I've been trying to run pysidecaster.py.  Understanding the command and trying just pycaster seems to work, so thanks for helping me to figure that one out.
For pysidecaster, however, there are multiple imports from PySide2, so removing it isn't an option.  However, in order for pycast to load requires the libraries provided, which have a duplicate copy of binaries for Qt.  Any thoughts on how to handle that?  I couldn't find anything on how to tell it explicitly which ones to use.

**Comment by dslunde** [comment]
Um, excuse me?

One of the issues I was asking about was in getting the pysidecaster.py file running, which still has conflicts, bugs and issues.  I've been waiting for a response to my previous comment from 15 days ago.  Why did this issue get closed without any update?

**Comment by clariusk** [comment]
thank you dslunde for the info. we found our packages have some symbols that should be pruned prior to releasing the binary, hence the PySide2 library and our library are both conflicting on the Qt dependencies. I have not seen this error on Linux (in fact that whole rpath thing was not an issue), so that could be an alternative platform to develop on for now. we'll try to address in future packages.
