### ISSUE TITLE
Cast Android 10.0.0 connection issue

### ISSUE THREAD

**Issue by daudrain** [clariusdev/cast#91]
Dear Clarius Support,

I did try out the Cast Android sample with Clarius 10.0.0 and the sample application fails to connect:
```
2022-10-05 15:20:00.328 13792-13792/me.clarius.sdk.cast.example I/Cast: Start
2022-10-05 15:20:00.330 13792-13792/me.clarius.sdk.cast.example I/Cast: Create
2022-10-05 15:20:00.365 13792-13792/me.clarius.sdk.cast.example D/Cast: Initialization result: true
2022-10-05 15:20:00.365 13792-15138/me.clarius.sdk.cast.example D/Cast: Firmware version: 10.0.0-458+a87863b0b8 (user param: V1)
2022-10-05 15:20:00.365 13792-15138/me.clarius.sdk.cast.example D/Cast: Firmware version: 10.0.0-444+a87863b0b8 (user param: HD)
2022-10-05 15:20:00.365 13792-15138/me.clarius.sdk.cast.example D/Cast: Firmware version: 10.0.0-444+a87863b0b8 (user param: HD3)
2022-10-05 15:20:13.269 13792-13792/me.clarius.sdk.cast.example D/Cast: Connecting to 192.168.1.1:5828
2022-10-05 15:20:13.275 13792-13792/me.clarius.sdk.cast.example E/Cast: Error: connect failure: Exception ocurred (Error connecting to TCP socket: Network is unreachable)
2022-10-05 15:20:13.276 13792-15138/me.clarius.sdk.cast.example D/Cast: Connection result: false
```

Clarius App looks to be correctly set since `research` mode is enabled and the app displays the usual ip/research port.

What's wrong with my setup?

Thank you
David 

![image](https://user-images.githubusercontent.com/3604504/194071111-2f721400-c420-4036-b473-e03a6b5014f0.png)

![image](https://user-images.githubusercontent.com/3604504/194071373-71a1822e-b51f-48a5-9f16-c7cc39142cb5.png)

**Comment by daudrain** [comment]
I tried Caster Qt project on Ubuntu 22.04 and it successfully connects/streams the US images

**Comment by julien-l** [comment]
I was able to reproduce:

* when running the Cast example app + Clarius App on the *same* device -> cannot connect, with error `Network is unreachable` but
* when running the Clarius App on a different device -> connection ok.

Can you confirm? If so, we will investigate.

Thanks,
Julien

**Comment by daudrain** [comment]
Hi Julien,

I confirm that running the Android App on another device, connection and stream are ok.

Note that if Clarius App is not hidden, the stream remains frozen: `toggle run` has no effect.

David

**Comment by daudrain** [comment]
Hi @julien-l ,

Have you been able to fix the issue?

Thank you

**Comment by julien-l** [comment]
No news yet, I will update you when I have more thanks!

**Comment by gzbykyasin** [comment]
When do you solve this problem @julien-l ? 
I got the same error too.

**Comment by julien-l** [comment]
Hello I found the issue: the socket created by the SDK was not bound to the network with [`android_setsocknetwork()`](https://developer.android.com/ndk/reference/group/networking#android_setsocknetwork).

To fix the issue, the network ID must be passed to the Cast SDK during connection. The Cast `connect()` function will be updated to accept the network ID as parameter.

This network ID is obtained from the `Network` object returned as parameter to the [`NetworkCallback.onAvailable()`](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onAvailable(android.net.Network)) callback. If using the Clarius Marketplace workflow where the Clarius App auto-joins the probe's Wi-Fi network and then launches the 3rd party app, this network ID will be passed in the launch intent.

This issue only occurs when using a network that was auto-joined with the [Android Wi-Fi Request API](https://developer.android.com/guide/topics/connectivity/wifi-bootstrap). The current workaround is the manually join the probe's Wi-Fi in the Android settings.

**Comment by ganitps** [comment]
Hi @julien-l
when will a new aar  with the new parameter in the connect function be released?
I’m not sure I understood the workaround but I tried to first connect the android device to the probes wifi
then open the clarius app than the example app, but still get the same errors.

**Comment by julien-l** [comment]
New binaries released at https://github.com/clariusdev/cast/releases.

Now the `connect()` function takes an extra parameter: the network ID, which is used by the cast SDK to bind the TCP port (used to communicate with the probe) to the Wi-Fi network. This should be only necessary when auto-joining the probe's Wi-Fi network, in other words: if you manually connect to the probe's Wi-Fi, it is not needed, in that case pass `0`.

Let me know if this works.

**Comment by ganitps** [comment]
Hi @julien-l ,
I finally got your workaround to work :slightly_smiling_face:. and it works well every time. with both sdk 10.0.0 and 10.1.1
Regarding the network id returned by the onAvailable()/onCapabilitiesChanged() callbacks they do not get called when auto connecting with the clarius app, only when the the wifi is connected manually (in that case we don’t need it.)
I’m new in the wifi P2P area, maybe I’m doing something wrong. do you have a stand alone  example where the network id is fetched from the ConnectivityManager?  using your example I get the same TCP error since the activity intent does not have “cus_network_id” extra.

**Comment by julien-l** [comment]
Hello @ganitps when Wi-Fi auto-join is done by the Clarius App, it is the Clarius App that receives the `onAvailable()` callback, not your client app, therefore you cannot obtain the necessary network ID to connect to the SDK.

In the Marketplace workflow (where the client app is launched from the Clarius App), that network ID is included in the launch intent. But when not using the Marketplace workflow, there is currently no way to obtain this network ID in the client app, we need to find a solution.

You could try to do the Wi-Fi auto-join in your own app (example: https://gist.github.com/julien-l/53756d4c3d40405290840dea7f8ddbcc) but I suspect it will move the issue to the Clarius App (it won't have the network ID). You can give it a try.

**Comment by ganitps** [comment]
Hello again @julien-l 
It's been a while.. I returned to working with cast and encountered an issue, I cant get any images..
I installed Clarius app on  a new tablet (Android 13) Clarius version : 10.2.1
scanner's software version updated to 10.2.0-477
I get these params in the intent:
network ID: 467262165005
IP address: 192.168.1.1
cast port: 5828

on the Cast.Listener I get
error()  =>  **software revisions are different** 
freeze () => true ..false..
**but no callbacks for images of any kind** (newProcessedImage / newRawImageFn / newSpectralImageFn)

any advice?

**Comment by julien-l** [comment]
Hello, 10.2.1 is a pilot release, we do not release APIs until it makes the store, please downgrade your scanners back to 10.1.
