### ISSUE TITLE
v10.0.0: import error

### ISSUE THREAD

**Issue by dm-ult** [clariusdev/cast#93]
I am unable to run the pycaster.py script using v10.0.0. I am getting the following import error:

![image](https://user-images.githubusercontent.com/30593574/196680396-d8010a82-079a-4d2f-891d-11a3a0fca637.png)

I am on Windows 11 using Python 3.8. I don't think it is a path issue as I have tried placing cast.dll, cast.lib and pyclariuscast.pyd in the same directory as pycaster.py.

Previously, I was able to import pyclariuscast when using v9.3.0 - I am not sure why it was working for v9.3.0 but not v10.0.0. I have tried updating to v10.0.0 in the same project and also creating a completely fresh project for v10.0.0 - both approaches give the same error.

Do you have any suggestions as to what else I might try?

Thanks!

**Comment by clariusk** [comment]
this thread may be relevant, https://github.com/clariusdev/cast/issues/84, it may be related to the python version, our v10 binaries are now using v3.9
