### ISSUE TITLE
Matching Layer Acoustic Impedance

### ISSUE THREAD

**Issue by aking316** [clariusdev/cast#94]
I am part of an engineering team working with a Clarius 1st Gen probe. My responsibility on this team is to determine the theoretical optimal acoustic impedance of a material that will function as an add-on to the clarius probe. I need to know the acoustic impedance of the outermost layer of the Clarius 1st Gen probe for my math to work. It is my responsibility to submit my work by the October 24th next monday.

Could you please provide the acoustic impedance of the last layer of the matching layer of the 1st Gen Clarius probe?

Thank you

**Comment by clariusk** [comment]
thanks for reaching out, unfortunately we do not have this data regarding our probe materials
