### ISSUE TITLE
Error: software revisions are different

### ISSUE THREAD

**Issue by Farah-Deeba** [clariusdev/cast#96]
The Cast API in the pc seems to get connected but shows an error that "software revisions are different". And it does not stream the RF data (when we press "Request," nothing happens).
![314607962_871417864019656_8151391641232114775_n](https://user-images.githubusercontent.com/22903055/200948903-3366382d-1564-4328-9657-485d889d6ffb.jpg)

**Comment by J-Olejnik** [comment]
Since 10.1.1 version of the IOS app is up and running, when will new binaries be available for download? Current ones (10.0.0) cause error mentioned above.

**Comment by julien-l** [comment]
New binaries released https://github.com/clariusdev/cast/releases thanks.
