### ISSUE TITLE
Hello Clarius support

### ISSUE THREAD

**Issue by nchavali-mai** [clariusdev/cast#98]
Hello Clarius support 

I am trying to use the cast API on my Windows laptop to steam the data from the Clarius device to my laptop. I am using python wrappers on top of the cast dlls provided by you. 

I get an error: 
**Error: could not authenticate certificate**

I get this when I am trying to connect when trying to use cast.dll from the python application. Any advice on how to get this resolved is greatly appreciated.

Regards
Neelima

**Comment by clariusk** [comment]
for the caller, you do not need the probe certificate, you should just pass "research" as the parameter, are you following this method?
